import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', region: 'Global' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', region: 'North India' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳', region: 'West Bengal / Bangladesh' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', region: 'Andhra Pradesh / Telangana' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳', region: 'Maharashtra' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', region: 'Tamil Nadu' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳', region: 'Gujarat' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳', region: 'Karnataka' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳', region: 'Kerala' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳', region: 'Punjab' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳', region: 'Odisha' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳', region: 'Assam' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇮🇳', region: 'North India' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', flag: '🇮🇳', region: 'Bihar / Jharkhand' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', flag: '🇮🇳', region: 'Classical' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', flag: '🇮🇳', region: 'Goa' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر', flag: '🇮🇳', region: 'Jammu & Kashmir' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', flag: '🇮🇳', region: 'Sindh region' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇮🇳', region: 'Northeast India' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্', flag: '🇮🇳', region: 'Manipur' },
  { code: 'bodo', name: 'Bodo', nativeName: 'बड़ो', flag: '🇮🇳', region: 'Assam' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', flag: '🇮🇳', region: 'Jammu' },
];

// UI translations for key phrases
export const TRANSLATIONS = {
  en: {
    selectLanguage: 'Select Your Language',
    selectSubtitle: 'Choose a language to get information in your preferred language',
    continueBtn: 'Continue',
    searchPlaceholder: 'Search language...',
    changeLanguage: 'Change Language',
    navHome: 'Home',
    navRecommend: 'Recommend',
    navMyFarm: 'My Farm',
    navHistory: 'History',
    navIntelligence: 'Intelligence',
    myFarmTitle: 'MY FARM',
    myFarmSubtitle: 'Manage your fields, track your soil, and plan smarter every season.',
    claySoil: 'Clay Soil',
    sandySoil: 'Sandy Soil',
    loamySoil: 'Loamy Soil',
    blackSoil: 'Black Soil',
    redSoil: 'Red Soil',
    alluvialSoil: 'Alluvial Soil',
    saveFieldBtn: 'Save Field',
    logCropBtn: 'Log Crop',
    addNewField: '+ Add New Field',
    logPastCrop: 'Log Past Crop',
    myFieldsHeader: 'MY FIELDS',
    farmOverviewHeader: 'Farm Overview',
    totalFieldsLabel: 'Total Fields',
    totalAcresLabel: 'Total Acres',
    soilTypesLabel: 'Soil Types',
    mostUsedLabel: 'Most used',
    cropHistoryHeader: 'CROP HISTORY',
    quickInsightsHeader: 'Quick Insights',
    analyzeBtn: 'Analyze',
    kharif: 'Kharif',
    rabi: 'Rabi',
    zaid: 'Zaid',
    goodYield: 'Good Yield',
    averageYield: 'Average',
    poorYield: 'Poor',
    welcomeBack: 'Welcome back',
    loginTitle: 'Login',
    username: 'Username',
    password: 'Password',
    loginBtn: 'Login',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    logout: 'Logout',
    allLanguages: 'All Languages',
    
    addField: 'Add Field',
    runAnalysis: 'Run Analysis',
    viewHistory: 'View History',
    activeCropsLabel: 'Active Crops',
    cropRecordsLabel: 'Crop Records',
    riskLevelLabel: 'Risk Level',
    successRate: 'Success Rate',
    
    // Farm Intelligence page translations
    farmIntelligenceSystem: 'FARM INTELLIGENCE SYSTEM',
    cropIntelligence: 'CROP INTELLIGENCE',
    cropIntelligenceSubtitle: 'Transforming your historical prediction logs into predictive analytics. Select any crop below to morph the operating system into a tailored crop diagnostics dashboard.',
    syncAtlasData: 'Sync Atlas Data',
    noAnalyticsFootprint: 'No Analytics Footprint Found',
    noAnalyticsFootprintSubtitle: 'This analytics center compiles crop statistics dynamically from your recommendation logs. Perform a soil diagnostic recommendation to boot up these neural widgets!',
    generateFirstRecommendation: 'GENERATE FIRST RECOMMENDATION',
    selectLoggedCropProfile: 'SELECT LOGGED CROP PROFILE',
    metricMatrix: 'METRIC MATRIX',
    climaticRanges: 'CLIMATIC RANGES',
    averageTemp: 'Average Temp',
    moistureAverage: 'Moisture Average',
    precipitation: 'Precipitation',
    dominantHarvestSeason: 'DOMINANT HARVEST SEASON',
    aiPredictiveConsistency: 'AI PREDICTIVE CONSISTENCY',
    evaluatedAcross: 'Evaluated across',
    chartProfile: 'CHART PROFILE',
    predictionHistoricalTimeline: 'PREDICTION HISTORICAL TIMELINE',
    realTimeChronoTimeline: 'REAL-TIME CHRONO TIMELINE',
    nitrogenAvg: 'Nitrogen Avg',
    phosphorusAvg: 'Phosphorus Avg',
    potassiumAvg: 'Potassium Avg',
    sensorDiagnostic: 'SENSOR DIAGNOSTIC',
    macronutrientBalance: 'MACRONUTRIENT BALANCE',
    optimalSoilType: 'OPTIMAL SOIL TYPE',
    diagnosticRiskProfile: 'DIAGNOSTIC RISK PROFILE',
    extremePHWarning: 'Warning: Extreme pH profile detected',
    phAlkalinityOptimum: 'pH alkalinity index optimum',
    basedOnPHCalculations: 'Based on average pH level calculations.',
    npkHeatmapIndex: 'NPK HEATMAP INDEX',
    macronutrientAllocationMatrix: 'MACRONUTRIENT ALLOCATION MATRIX',
    allocatedIndicesNotice: '*Allocated indices represent relative chemical proportions extracted across sequential prediction cycles.',
    dynamicAIInsights: 'DYNAMIC AI INSIGHTS',
    aiInsightsVerified: 'AgroXAI Cognitive Operations Verified',
    recentActivity: 'Recent Activity',
    soilHealthOverview: 'Soil Health Overview',
    precisionAnalysisHistory: 'Precision Analysis History',
    
    // Crop names translations
    muskmelon: 'Muskmelon',
    chickpea: 'Chickpea',
    rice: 'Rice',
    cotton: 'Cotton',
    wheat: 'Wheat',
    
    // Insight details
    insight1Detail: 'Historical predictions confirm high enzymatic compatibility in soil profile indices.',
    insight2GrowthDetail: 'Foliar volume benchmarks show excellent nitrogen absorption coefficients.',
    insight2WarningDetail: 'Macronutrient deficiencies limit core photosynthetic output velocities.',
    insight3Detail: 'Climatic telemetry vectors fit the seasonal humidity range perfectly.',
  },
  hi: {
    selectLanguage: 'अपनी भाषा चुनें',
    selectSubtitle: 'अपनी पसंदीदा भाषा में जानकारी प्राप्त करने के लिए एक भाषा चुनें',
    continueBtn: 'जारी रखें',
    searchPlaceholder: 'भाषा खोजें...',
    changeLanguage: 'भाषा बदलें',
    navHome: 'होम',
    navRecommend: 'सिफारिश',
    navMyFarm: 'मेरा खेत',
    navHistory: 'इतिहास',
    navIntelligence: 'बुद्धिमत्ता',
    myFarmTitle: 'मेरा फार्म',
    myFarmSubtitle: 'अपने खेतों का प्रबंधन करें, अपनी मिट्टी को ट्रैक करें, और हर मौसम में स्मार्ट योजना बनाएं।',
    claySoil: 'चिकनी मिट्टी',
    sandySoil: 'रेतीली मिट्टी',
    loamySoil: 'दुमट मिट्टी',
    blackSoil: 'काली मिट्टी',
    redSoil: 'लाल मिट्टी',
    alluvialSoil: 'जलोढ़ मिट्टी',
    saveFieldBtn: 'खेत सहेजें',
    logCropBtn: 'फसल दर्ज करें',
    addNewField: '+ नया खेत जोड़ें',
    logPastCrop: 'पिछली फसल दर्ज करें',
    myFieldsHeader: 'मेरे खेत',
    farmOverviewHeader: 'फार्म सिंहावलोकन',
    totalFieldsLabel: 'कुल खेत',
    totalAcresLabel: 'कुल क्षेत्र',
    soilTypesLabel: 'मिट्टी के प्रकार',
    mostUsedLabel: 'सबसे अधिक उपयोग किया गया',
    cropHistoryHeader: 'फसल का इतिहास',
    quickInsightsHeader: 'त्वरित अंतर्दृष्टि',
    analyzeBtn: 'विश्लेषण करें',
    kharif: 'खरीफ',
    rabi: 'रबी',
    zaid: 'जायद',
    goodYield: 'अच्छा उत्पादन',
    averageYield: 'औसत',
    poorYield: 'कमजोर',
    welcomeBack: 'वापसी पर स्वागत है',
    loginTitle: 'लॉगिन',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    loginBtn: 'लॉगिन करें',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    logout: 'लॉग आउट',
    allLanguages: 'सभी भाषाएँ',
    
    addField: 'खेत जोड़ें',
    runAnalysis: 'विश्लेषण चलाएं',
    viewHistory: 'इतिहास देखें',
    activeCropsLabel: 'सक्रिय फसलें',
    cropRecordsLabel: 'फसल रिकॉर्ड',
    riskLevelLabel: 'जोखिम स्तर',
    successRate: 'सफलता दर',
    
    // Farm Intelligence page translations
    farmIntelligenceSystem: 'फार्म इंटेलिजेंस सिस्टम',
    cropIntelligence: 'फसल बुद्धि',
    cropIntelligenceSubtitle: 'अपने ऐतिहासिक पूर्वानुमान लॉग को भविष्य कहनेवाला विश्लेषण में बदलना। नीचे किसी भी फसल का चयन करके ऑपरेटिंग सिस्टम को एक विशेष फसल निदान डैशबोर्ड में बदलें।',
    syncAtlasData: 'एटलस डेटा सिंक करें',
    noAnalyticsFootprint: 'कोई विश्लेषण फ़ुटप्रिंट नहीं मिला',
    noAnalyticsFootprintSubtitle: 'यह विश्लेषण केंद्र आपके सिफ़ारिश लॉग से गतिशील रूप से फ़सल के आँकड़े संकलित करता है। इन न्यूरल विगेट्स को बूट करने के लिए एक मिट्टी निदान सिफ़ारिश करें!',
    generateFirstRecommendation: 'पहली सिफारिश उत्पन्न करें',
    selectLoggedCropProfile: 'लॉग की गई फसल प्रोफाइल चुनें',
    metricMatrix: 'मीट्रिक मैट्रिक्स',
    climaticRanges: 'जलवायु रेंज',
    averageTemp: 'औसत तापमान',
    moistureAverage: 'औसत नमी',
    precipitation: 'वर्षा',
    dominantHarvestSeason: 'मुख्य फसल सीजन',
    aiPredictiveConsistency: 'एआई भविष्य कहनेवाला संगति',
    evaluatedAcross: 'मूल्यांकन किया गया',
    chartProfile: 'चार्ट प्रोफाइल',
    predictionHistoricalTimeline: 'पूर्वानुमान का इतिहास समयरेखा',
    realTimeChronoTimeline: 'वास्तविक समय इतिहास समयरेखा',
    nitrogenAvg: 'औसत नाइट्रोजन',
    phosphorusAvg: 'औसत फास्फोरस',
    potassiumAvg: 'औसत पोटेशियम',
    sensorDiagnostic: 'सेंसर निदान',
    macronutrientBalance: 'मैक्रोन्यूट्रिएंट संतुलन',
    optimalSoilType: 'इष्टतम मिट्टी का प्रकार',
    diagnosticRiskProfile: 'निदान जोखिम प्रोफाइल',
    extremePHWarning: 'चेतावनी: अत्यधिक पीएच प्रोफाइल पाया गया',
    phAlkalinityOptimum: 'पीएच क्षारीयता सूचकांक इष्टतम',
    basedOnPHCalculations: 'औसत पीएच स्तर गणना पर आधारित।',
    npkHeatmapIndex: 'एनपीके हीटमैप इंडेक्स',
    macronutrientAllocationMatrix: 'मैक्रोन्यूट्रिएंट आवंटन मैट्रिक्स',
    allocatedIndicesNotice: '*आवंटित सूचकांक अनुक्रमिक पूर्वानुमान चक्रों में निकाले गए सापेक्ष रासायनिक अनुपात का प्रतिनिधित्व करते हैं।',
    dynamicAIInsights: 'गतिशील एआई अंतर्दृष्टि',
    aiInsightsVerified: 'एग्रोएक्सएआई संज्ञानात्मक संचालन सत्यापित',
    recentActivity: 'हाल की गतिविधि',
    soilHealthOverview: 'मृदा स्वास्थ्य सिंहावलोकन',
    precisionAnalysisHistory: 'सटीक विश्लेषण इतिहास',
    
    // Crop names translations
    muskmelon: 'खरबूजा',
    chickpea: 'चना',
    rice: 'चावल',
    cotton: 'कपास',
    wheat: 'गेहूं',
    
    // Insight details
    insight1Detail: 'ऐतिहासिक भविष्यवाणियां मिट्टी के प्रोफाइल सूचकांकों में उच्च एंजाइमी संगतता की पुष्टि करती हैं।',
    insight2GrowthDetail: 'पर्ण मात्रा बेंचमार्क उत्कृष्ट नाइट्रोजन अवशोषण गुणांक दिखाते हैं।',
    insight2WarningDetail: 'मैक्रोन्यूट्रिएंट की कमी मुख्य प्रकाश संश्लेषक उत्पादन वेग को सीमित करती है।',
    insight3Detail: 'जलवायु टेलीमेट्री वेक्टर मौसमी आर्द्रता सीमा में पूरी तरह फिट बैठते हैं।',
  },
  bn: {
    selectLanguage: 'আপনার ভাষা বেছে নিন',
    selectSubtitle: 'আপনার পছন্দের ভাষায় তথ্য পেতে একটি ভাষা বেছে নিন',
    continueBtn: 'এগিয়ে যান',
    searchPlaceholder: 'ভাষা খুঁজুন...',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
    navHome: 'হোম',
    navRecommend: 'সুপারিশ',
    navHistory: 'ইতিহাস',
    welcomeBack: 'আবার স্বাগতম',
    loginTitle: 'লগইন',
    username: 'ব্যবহারকারীর নাম',
    password: 'পাসওয়ার্ড',
    loginBtn: 'লগইন করুন',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signUp: 'সাইন আপ করুন',
    logout: 'লগ আউট',
    allLanguages: 'সব ভাষা',
  },
  te: {
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    selectSubtitle: 'మీకు ఇష్టమైన భాషలో సమాచారం పొందడానికి ఒక భాషను ఎంచుకోండి',
    continueBtn: 'కొనసాగించు',
    searchPlaceholder: 'భాష వెతకండి...',
    changeLanguage: 'భాష మార్చండి',
    navHome: 'హోమ్',
    navRecommend: 'సిఫార్సు',
    navHistory: 'చరిత్ర',
    navMyFarm: 'నా పొలం',
    myFarmTitle: 'నా పొలం',
    myFarmSubtitle: 'మీ ఫీల్డ్‌లను నిర్వహించండి, మీ మట్టిని ట్రాక్ చేయండి మరియు ప్రతి సీజన్‌లో తెలివిగా ప్లాన్ చేయండి.',
    claySoil: 'బంకమట్టి',
    sandySoil: 'ఇసుక నేల',
    loamySoil: 'లోమీ నేల',
    blackSoil: 'నల్ల రేగడి నేల',
    redSoil: 'ఎర్ర నేల',
    alluvialSoil: 'ఒండ్రు నేల',
    saveFieldBtn: 'ఫీల్డ్ సేవ్ చేయండి',
    logCropBtn: 'పంటను లాగ్ చేయండి',
    addNewField: '+ కొత్త ఫీల్డ్‌ని జోడించండి',
    logPastCrop: 'పాత పంటను లాగ్ చేయండి',
    myFieldsHeader: 'నా పొలాలు',
    farmOverviewHeader: 'ఫామ్ అవలోకనం',
    totalFieldsLabel: 'మొత్తం పొలాలు',
    totalAcresLabel: 'మొత్తం ఎకరాలు',
    soilTypesLabel: 'మట్టి రకాలు',
    mostUsedLabel: 'ఎక్కువగా ఉపయోగించినవి',
    cropHistoryHeader: 'పంట చరిత్ర',
    quickInsightsHeader: 'త్వరిత అంతర్దృష్టులు',
    analyzeBtn: 'విశ్లేషించండి',
    kharif: 'ఖరీఫ్',
    rabi: 'రబీ',
    zaid: 'జైద్',
    goodYield: 'మంచి దిగుబడి',
    averageYield: 'సగటు',
    poorYield: 'తక్కువ',
    welcomeBack: 'తిరిగి స్వాగతం',
    loginTitle: 'లాగిన్',
    username: 'వినియోగదారు పేరు',
    password: 'పాస్వర్డ్',
    loginBtn: 'లాగిన్ చేయండి',
    noAccount: 'ఖాతా లేదా?',
    signUp: 'సైన్ అప్',
    logout: 'లాగ్ అవుట్',
    allLanguages: 'అన్ని భాషలు',
  },
  mr: {
    selectLanguage: 'तुमची भाषा निवडा',
    selectSubtitle: 'तुमच्या आवडत्या भाषेत माहिती मिळविण्यासाठी भाषा निवडा',
    continueBtn: 'पुढे जा',
    searchPlaceholder: 'भाषा शोधा...',
    changeLanguage: 'भाषा बदला',
    navHome: 'मुखपृष्ठ',
    navRecommend: 'शिफारस',
    navHistory: 'इतिहास',
    welcomeBack: 'परत स्वागत आहे',
    loginTitle: 'लॉगिन',
    username: 'वापरकर्तानाव',
    password: 'पासवर्ड',
    loginBtn: 'लॉगिन करा',
    noAccount: 'खाते नाही?',
    signUp: 'साइन अप करा',
    logout: 'लॉग आउट',
    allLanguages: 'सर्व भाषा',
  },
  ta: {
    selectLanguage: 'உங்கள் மொழியை தேர்ந்தெடுங்கள்',
    selectSubtitle: 'உங்கள் விருப்பமான மொழியில் தகவல்களைப் பெற ஒரு மொழியைத் தேர்ந்தெடுங்கள்',
    continueBtn: 'தொடரவும்',
    searchPlaceholder: 'மொழி தேடுங்கள்...',
    changeLanguage: 'மொழி மாற்றுங்கள்',
    navHome: 'முகப்பு',
    navRecommend: 'பரிந்துரை',
    navHistory: 'வரலாறு',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    loginTitle: 'உள்நுழைவு',
    username: 'பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    loginBtn: 'உள்நுழைக',
    noAccount: 'கணக்கு இல்லையா?',
    signUp: 'பதிவு செய்க',
    logout: 'வெளியேறு',
    allLanguages: 'அனைத்து மொழிகள்',
  },
  gu: {
    selectLanguage: 'તમારી ભાષા પસંદ કરો',
    selectSubtitle: 'તમારી પસંદની ભાષામાં માહિતી મેળવવા ભાષા પસંદ કરો',
    continueBtn: 'આગળ વધો',
    searchPlaceholder: 'ભાષા શોધો...',
    changeLanguage: 'ભાષા બદલો',
    navHome: 'હોમ',
    navRecommend: 'ભલામણ',
    navHistory: 'ઇતિહાસ',
    welcomeBack: 'પાછા સ્વાગત છે',
    loginTitle: 'લૉગિન',
    username: 'વપરાશકર્તાનું નામ',
    password: 'પાસવર્ડ',
    loginBtn: 'લૉગિન કરો',
    noAccount: 'ખાતું નથી?',
    signUp: 'સાઇન અપ',
    logout: 'લૉગ આઉટ',
    allLanguages: 'બધી ભાષાઓ',
  },
  kn: {
    selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    selectSubtitle: 'ನಿಮಗೆ ಇಷ್ಟವಾದ ಭಾಷೆಯಲ್ಲಿ ಮಾಹಿತಿ ಪಡೆಯಲು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    continueBtn: 'ಮುಂದುವರಿಯಿರಿ',
    searchPlaceholder: 'ಭಾಷೆ ಹುಡುಕಿ...',
    changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
    navHome: 'ಮನೆ',
    navRecommend: 'ಶಿಫಾರಸು',
    navHistory: 'ಇತಿಹಾಸ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    loginTitle: 'ಲಾಗಿನ್',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್ವರ್ಡ್',
    loginBtn: 'ಲಾಗಿನ್ ಮಾಡಿ',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    signUp: 'ಸೈನ್ ಅಪ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    allLanguages: 'ಎಲ್ಲಾ ಭಾಷೆಗಳು',
  },
  ml: {
    selectLanguage: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    selectSubtitle: 'നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷയിൽ വിവരങ്ങൾ നേടാൻ ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
    continueBtn: 'തുടരുക',
    searchPlaceholder: 'ഭാഷ തിരയുക...',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    navHome: 'ഹോം',
    navRecommend: 'ശുപാർശ',
    navHistory: 'ചരിത്രം',
    welcomeBack: 'തിരിച്ചു സ്വാഗതം',
    loginTitle: 'ലോഗിൻ',
    username: 'ഉപയോക്തൃ നാമം',
    password: 'പാസ്‌വേഡ്',
    loginBtn: 'ലോഗിൻ ചെയ്യുക',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    signUp: 'സൈൻ അപ്',
    logout: 'ലോഗ് ഔട്ട്',
    allLanguages: 'എല്ലാ ഭാഷകളും',
  },
  pa: {
    selectLanguage: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    selectSubtitle: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਵਿੱਚ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਇੱਕ ਭਾਸ਼ਾ ਚੁਣੋ',
    continueBtn: 'ਜਾਰੀ ਰੱਖੋ',
    searchPlaceholder: 'ਭਾਸ਼ਾ ਖੋਜੋ...',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    navHome: 'ਹੋਮ',
    navRecommend: 'ਸਿਫਾਰਿਸ਼',
    navHistory: 'ਇਤਿਹਾਸ',
    welcomeBack: 'ਵਾਪਸ ਜੀ ਆਇਆਂ',
    loginTitle: 'ਲਾਗਇਨ',
    username: 'ਉਪਭੋਗਤਾ ਨਾਮ',
    password: 'ਪਾਸਵਰਡ',
    loginBtn: 'ਲਾਗਇਨ ਕਰੋ',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ?',
    signUp: 'ਸਾਈਨ ਅਪ',
    logout: 'ਲੌਗ ਆਊਟ',
    allLanguages: 'ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ',
  },
};

// Get translation for a key, fallback to English
export const getTranslation = (lang, key) => {
  return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['en'][key] ?? key;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('cv_language') || 'en';
  });
  const [languageSelected, setLanguageSelected] = useState(() => {
    return localStorage.getItem('cv_language_selected') === 'true';
  });

  const selectLanguage = (code) => {
    setLanguage(code);
    setLanguageSelected(true);
    localStorage.setItem('cv_language', code);
    localStorage.setItem('cv_language_selected', 'true');
  };

  const resetLanguageSelection = () => {
    setLanguageSelected(false);
    localStorage.removeItem('cv_language_selected');
  };

  const t = (key) => getTranslation(language, key);

  const currentLanguage = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{
      language,
      languageSelected,
      currentLanguage,
      selectLanguage,
      resetLanguageSelection,
      t,
      LANGUAGES,
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
