import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', region: 'Global' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', region: 'North India' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳', region: 'West Bengal / Bangladesh' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', region: 'Andhra Pradesh / Telangana' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳', region: 'Maharashtra' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', region: 'Tamil Nadu' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳', region: 'Gujarat' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳', region: 'Karnataka' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳', region: 'Kerala' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳', region: 'Punjab' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳', region: 'Odisha' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳', region: 'Assam' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇮🇳', region: 'North India' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', flag: '🇮🇳', region: 'Bihar / Jharkhand' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', flag: '🇮🇳', region: 'Classical' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', flag: '🇮🇳', region: 'Goa' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر', flag: '🇮🇳', region: 'Jammu & Kashmir' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', flag: '🇮🇳', region: 'Sindh region' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇮🇳', region: 'Northeast India' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্', flag: '🇮🇳', region: 'Manipur' },
  { code: 'bodo', name: 'Bodo', nativeName: 'बड़ो', flag: '🇮🇳', region: 'Assam' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', flag: '🇮🇳', region: 'Jammu' },
];

// UI translations for key phrases
export const TRANSLATIONS = {
  en: {
    selectLanguage: 'Select Your Language',
    selectSubtitle: 'Choose a language to get information in your preferred language',
    continueBtn: 'Continue',
    searchPlaceholder: 'Search language...',
    changeLanguage: 'Change Language',
    navHome: 'Home',
    navRecommend: 'Recommend',
    navMyFarm: 'My Farm',
    navHistory: 'History',
    navIntelligence: 'Intelligence',
    myFarmTitle: 'MY FARM',
    myFarmSubtitle: 'Manage your fields, track your soil, and plan smarter every season.',
    claySoil: 'Clay Soil',
    sandySoil: 'Sandy Soil',
    loamySoil: 'Loamy Soil',
    blackSoil: 'Black Soil',
    redSoil: 'Red Soil',
    alluvialSoil: 'Alluvial Soil',
    saveFieldBtn: 'Save Field',
    logCropBtn: 'Log Crop',
    addNewField: '+ Add New Field',
    logPastCrop: 'Log Past Crop',
    myFieldsHeader: 'MY FIELDS',
    farmOverviewHeader: 'Farm Overview',
    totalFieldsLabel: 'Total Fields',
    totalAcresLabel: 'Total Acres',
    soilTypesLabel: 'Soil Types',
    mostUsedLabel: 'Most used',
    cropHistoryHeader: 'CROP HISTORY',
    quickInsightsHeader: 'Quick Insights',
    analyzeBtn: 'Analyze',
    kharif: 'Kharif',
    rabi: 'Rabi',
    zaid: 'Zaid',
    goodYield: 'Good Yield',
    averageYield: 'Average',
    poorYield: 'Poor',
    welcomeBack: 'Welcome back',
    loginTitle: 'Login',
    username: 'Username',
    password: 'Password',
    loginBtn: 'Login',
    noAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    logout: 'Logout',
    allLanguages: 'All Languages',
    addField: 'Add Field',
    runAnalysis: 'Run Analysis',
    viewHistory: 'View History',
    activeCropsLabel: 'Active Crops',
    cropRecordsLabel: 'Crop Records',
    riskLevelLabel: 'Risk Level',
    successRate: 'Success Rate',
    farmIntelligenceSystem: 'FARM INTELLIGENCE SYSTEM',
    cropIntelligence: 'CROP INTELLIGENCE',
    cropIntelligenceSubtitle: 'Transforming your historical prediction logs into predictive analytics. Select any crop below to morph the operating system into a tailored crop diagnostics dashboard.',
    syncAtlasData: 'Sync Atlas Data',
    noAnalyticsFootprint: 'No Analytics Footprint Found',
    noAnalyticsFootprintSubtitle: 'This analytics center compiles crop statistics dynamically from your recommendation logs. Perform a soil diagnostic recommendation to boot up these neural widgets!',
    generateFirstRecommendation: 'GENERATE FIRST RECOMMENDATION',
    selectLoggedCropProfile: 'SELECT LOGGED CROP PROFILE',
    metricMatrix: 'METRIC MATRIX',
    climaticRanges: 'CLIMATIC RANGES',
    averageTemp: 'Average Temp',
    moistureAverage: 'Moisture Average',
    precipitation: 'Precipitation',
    dominantHarvestSeason: 'DOMINANT HARVEST SEASON',
    aiPredictiveConsistency: 'AI PREDICTIVE CONSISTENCY',
    evaluatedAcross: 'Evaluated across',
    chartProfile: 'CHART PROFILE',
    predictionHistoricalTimeline: 'PREDICTION HISTORICAL TIMELINE',
    realTimeChronoTimeline: 'REAL-TIME CHRONO TIMELINE',
    nitrogenAvg: 'Nitrogen Avg',
    phosphorusAvg: 'Phosphorus Avg',
    potassiumAvg: 'Potassium Avg',
    sensorDiagnostic: 'SENSOR DIAGNOSTIC',
    macronutrientBalance: 'MACRONUTRIENT BALANCE',
    optimalSoilType: 'OPTIMAL SOIL TYPE',
    diagnosticRiskProfile: 'DIAGNOSTIC RISK PROFILE',
    extremePHWarning: 'Warning: Extreme pH profile detected',
    phAlkalinityOptimum: 'pH alkalinity index optimum',
    basedOnPHCalculations: 'Based on average pH level calculations.',
    npkHeatmapIndex: 'NPK HEATMAP INDEX',
    macronutrientAllocationMatrix: 'MACRONUTRIENT ALLOCATION MATRIX',
    allocatedIndicesNotice: '*Allocated indices represent relative chemical proportions extracted across sequential prediction cycles.',
    dynamicAIInsights: 'DYNAMIC AI INSIGHTS',
    aiInsightsVerified: 'AgroXAI Cognitive Operations Verified',
    recentActivity: 'Recent Activity',
    soilHealthOverview: 'Soil Health Overview',
    precisionAnalysisHistory: 'Precision Analysis History',
    muskmelon: 'Muskmelon',
    chickpea: 'Chickpea',
    rice: 'Rice',
    cotton: 'Cotton',
    wheat: 'Wheat',
    insight1Detail: 'Historical predictions confirm high enzymatic compatibility in soil profile indices.',
    insight2GrowthDetail: 'Foliar volume benchmarks show excellent nitrogen absorption coefficients.',
    insight2WarningDetail: 'Macronutrient deficiencies limit core photosynthetic output velocities.',
    insight3Detail: 'Climatic telemetry vectors fit the seasonal humidity range perfectly.',
  },
  hi: {
    selectLanguage: 'अपनी भाषा चुनें',
    selectSubtitle: 'अपनी पसंदीदा भाषा में जानकारी प्राप्त करने के लिए एक भाषा चुनें',
    continueBtn: 'जारी रखें',
    searchPlaceholder: 'भाषा खोजें...',
    changeLanguage: 'भाषा बदलें',
    navHome: 'होम',
    navRecommend: 'सिफारिश',
    navMyFarm: 'मेरा खेत',
    navHistory: 'इतिहास',
    navIntelligence: 'बुद्धिमत्ता',
    myFarmTitle: 'मेरा फार्म',
    myFarmSubtitle: 'अपने खेतों का प्रबंधन करें, अपनी मिट्टी को ट्रैक करें, और हर मौसम में स्मार्ट योजना बनाएं।',
    claySoil: 'चिकनी मिट्टी',
    sandySoil: 'रेतीली मिट्टी',
    loamySoil: 'दुमट मिट्टी',
    blackSoil: 'काली मिट्टी',
    redSoil: 'लाल मिट्टी',
    alluvialSoil: 'जलोढ़ मिट्टी',
    saveFieldBtn: 'खेत सहेजें',
    logCropBtn: 'फसल दर्ज करें',
    addNewField: '+ नया खेत जोड़ें',
    logPastCrop: 'पिछली फसल दर्ज करें',
    myFieldsHeader: 'मेरे खेत',
    farmOverviewHeader: 'फार्म सिंहावलोकन',
    totalFieldsLabel: 'कुल खेत',
    totalAcresLabel: 'कुल क्षेत्र',
    soilTypesLabel: 'मिट्टी के प्रकार',
    mostUsedLabel: 'सबसे अधिक उपयोग किया गया',
    cropHistoryHeader: 'फसल का इतिहास',
    quickInsightsHeader: 'त्वरित अंतर्दृष्टि',
    analyzeBtn: 'विश्लेषण करें',
    kharif: 'खरीफ',
    rabi: 'रबी',
    zaid: 'जायद',
    goodYield: 'अच्छा उत्पादन',
    averageYield: 'औसत',
    poorYield: 'कमजोर',
    welcomeBack: 'वापसी पर स्वागत है',
    loginTitle: 'लॉगिन',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    loginBtn: 'लॉगिन करें',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    logout: 'लॉग आउट',
    allLanguages: 'सभी भाषाएँ',
    addField: 'खेत जोड़ें',
    runAnalysis: 'विश्लेषण चलाएं',
    viewHistory: 'इतिहास देखें',
    activeCropsLabel: 'सक्रिय फसलें',
    cropRecordsLabel: 'फसल रिकॉर्ड',
    riskLevelLabel: 'जोखिम स्तर',
    successRate: 'सफलता दर',
    farmIntelligenceSystem: 'फार्म इंटेलिजेंस सिस्टम',
    cropIntelligence: 'फसल बुद्धि',
    cropIntelligenceSubtitle: 'अपने ऐतिहासिक पूर्वानुमान लॉग को भविष्य कहनेवाला विश्लेषण में बदलना। नीचे किसी भी फसल का चयन करके ऑपरेटिंग सिस्टम को एक विशेष फसल निदान डैशबोर्ड में बदलें।',
    syncAtlasData: 'एटलस डेटा सिंक करें',
    noAnalyticsFootprint: 'कोई विश्लेषण फ़ुटप्रिंट नहीं मिला',
    noAnalyticsFootprintSubtitle: 'यह विश्लेषण केंद्र आपके सिफ़ারिश लॉग से गतिशील रूप से फ़सल के आँकड़े संकलিত करता है। इन न्यूरल विगेट्स को बूट करने के लिए एक मिट्टी निदान सिफ़ารिश करें!',
    generateFirstRecommendation: 'पहली सिफारिश उत्पन्न करें',
    selectLoggedCropProfile: 'लॉग की गई फसल प्रोफाइल चुनें',
    metricMatrix: 'मीट्रिक मैट्रिक्स',
    climaticRanges: 'जलवायु रेंज',
    averageTemp: 'औसत तापमान',
    moistureAverage: 'औसत नमी',
    precipitation: 'वर्षा',
    dominantHarvestSeason: 'मुख्य फसल सीजन',
    aiPredictiveConsistency: 'एआई भविष्य कहनेवाला संगति',
    evaluatedAcross: 'मूल्यांकन किया गया',
    chartProfile: 'चार्ट प्रोफाइल',
    predictionHistoricalTimeline: 'पूर्वानुमान का इतिहास समयरेखा',
    realTimeChronoTimeline: 'वास्तविक समय इतिहास समयरेखा',
    nitrogenAvg: 'औसत नाइट्रोजन',
    phosphorusAvg: 'औसत फास्फोरस',
    potassiumAvg: 'औसत पोटेशियम',
    sensorDiagnostic: 'सेंसर निदान',
    macronutrientBalance: 'मैक्रोन्यूट्रिएंट संतुलन',
    optimalSoilType: 'इष्टतम मिट्टी का प्रकार',
    diagnosticRiskProfile: 'निदान जोखिम प्रोफाइल',
    extremePHWarning: 'चेतावनी: अत्यधिक पीएच प्रोफाइल पाया गया',
    phAlkalinityOptimum: 'पीएच क्षारीयता सूचकांक इष्टतम',
    basedOnPHCalculations: 'औसत पीएच स्तर गणना पर आधारित।',
    npkHeatmapIndex: 'एनपीके हीटमैप इंडेक्स',
    macronutrientAllocationMatrix: 'मैक्रोन्यूट्रिएंट आवंटन मैट्रिक्स',
    allocatedIndicesNotice: '*आवंटित सूचकांक अनुक्रमिक पूर्वानुमान चक्रों में निकाले गए सापेक्ष रासायनिक अनुपात का प्रतिनिधित्व करते हैं।',
    dynamicAIInsights: 'गतिशील एआई अंतर्दृष्टि',
    aiInsightsVerified: 'एग्रोएक्सएआई संज्ञानात्मक संचालन सत्यापित',
    recentActivity: 'हाल की गतिविधि',
    soilHealthOverview: 'मृदा स्वास्थ्य सिंहावलोकन',
    precisionAnalysisHistory: 'सटीक विश्लेषण इतिहास',
    muskmelon: 'खरबूजा',
    chickpea: 'चना',
    rice: 'चावल',
    cotton: 'कपास',
    wheat: 'गेहूं',
    insight1Detail: 'ऐतिहासिक भविष्यवाणियां मिट्टी के प्रोफाइल सूचकांकों में उच्च एंजाइमी संगतता की पुष्टि करती करती हैं।',
    insight2GrowthDetail: 'पर्ण मात्रा बेंचमार्क उत्कृष्ट नाइट्रोजन अवशोषण गुणांक दिखाते हैं।',
    insight2WarningDetail: 'मैक्रोन्यूट्रिएंट की कमी मुख्य प्रकाश संश्लेषक उत्पादन वेग को सीमित करती है।',
    insight3Detail: 'जलवायु टेलीमेट्री वेक्टर मौसमी आर्द्रता सीमा में पूरी तरह फिट बैठते हैं।',
  },
  bn: {
    selectLanguage: 'আপনার ভাষা বেছে নিন',
    selectSubtitle: 'আপনার পছন্দের ভাষায় তথ্য পেতে একটি ভাষা বেছে নিন',
    continueBtn: 'এগিয়ে যান',
    searchPlaceholder: 'ভাষা খুঁজুন...',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
    navHome: 'হোম',
    navRecommend: 'সুপারিশ',
    navHistory: 'ইতিহাস',
    welcomeBack: 'আবার স্বাগতম',
    loginTitle: 'লগইন',
    username: 'ব্যবহারকারীর নাম',
    password: 'পাসওয়ার্ড',
    loginBtn: 'লগইন করুন',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signUp: 'সাইন আপ করুন',
    logout: 'লগ আউট',
    allLanguages: 'সব ভাষা',
    navMyFarm: 'আমার খামার',
    navIntelligence: 'বুদ্ধিমত্তা',
    myFarmTitle: 'আমার খামার',
    myFarmSubtitle: 'আপনার ক্ষেত্রগুলি পরিচালনা করুন, আপনার মাটি ট্র্যাক করুন এবং প্রতি ঋতুতে আরও স্মার্ট পরিকল্পনা করুন।',
    claySoil: 'এঁটেল মাটি',
    sandySoil: 'বালুকাময় মাটি',
    loamySoil: 'দোআঁশ মাটি',
    blackSoil: 'কালো মাটি',
    redSoil: 'লাল মাটি',
    alluvialSoil: 'পলিমাটি',
    saveFieldBtn: 'ক্ষেত্র সংরক্ষণ করুন',
    logCropBtn: 'লগ ক্রপ',
    addNewField: '+ নতুন ক্ষেত্র যোগ করুন',
    logPastCrop: 'লগ অতীত ক্রপ',
    myFieldsHeader: 'আমার ক্ষেত্র',
    farmOverviewHeader: 'খামার ওভারভিউ',
    totalFieldsLabel: 'মোট ক্ষেত্র',
    totalAcresLabel: 'মোট একর',
    soilTypesLabel: 'মাটির ধরন',
    mostUsedLabel: 'সর্বাধিক ব্যবহৃত',
    cropHistoryHeader: 'ফসলের ইতিহাস',
    quickInsightsHeader: 'দ্রুত অন্তর্দৃষ্টি',
    analyzeBtn: 'বিশ্লেষণ করুন',
    kharif: 'খরিফ',
    rabi: 'রাবি',
    zaid: 'যায়েদ',
    goodYield: 'ভালো ফলন',
    averageYield: 'গড়',
    poorYield: 'দরিদ্র',
    addField: 'ক্ষেত্র যোগ করুন',
    runAnalysis: 'বিশ্লেষণ চালান',
    viewHistory: 'ইতিহাস দেখুন',
    activeCropsLabel: 'সক্রিয় ফসল',
    cropRecordsLabel: 'ফসলের রেকর্ড',
    riskLevelLabel: 'ঝুঁকির স্তর',
    successRate: 'সাফল্যের হার',
    farmIntelligenceSystem: 'ফার্ম ইন্টেলিজেন্স সিস্টেম',
    cropIntelligence: 'ক্রপ ইন্টেলিজেন্স',
    cropIntelligenceSubtitle: 'আপনার ঐতিহাসিক ভবিষ্যদ্বাণী লগগুলিকে ভবিষ্যদ্বাণীমূলক বিশ্লেষণে রূপান্তর করা হচ্ছে। অপারেটিং সিস্টেমটিকে একটি উপযুক্ত ক্রপ ডায়াগনস্টিক ড্যাশবোর্ডে রূপান্তর করতে নীচের যেকোনো ফসল নির্বাচন করুন।',
    syncAtlasData: 'অ্যাটলাস ডেটা সিঙ্ক করুন',
    noAnalyticsFootprint: 'কোনো অ্যানালিটিক্স ফুটপ্রিন্ট পাওয়া যায়নি',
    noAnalyticsFootprintSubtitle: 'এই বিশ্লেষণ কেন্দ্র আপনার সুপারিশ লগ থেকে গতিশীলভাবে ফসল পরিসংখ্যান সংকলন. এই নিউরাল উইজেটগুলি বুট আপ করার জন্য একটি মাটি ডায়াগনস্টিক সুপারিশ সম্পাদন করুন!',
    generateFirstRecommendation: 'প্রথম সুপারিশ জেনারেট করুন',
    selectLoggedCropProfile: 'লগ করা ক্রপ প্রোফাইল নির্বাচন করুন',
    metricMatrix: 'মেট্রিক ম্যাট্রিক্স',
    climaticRanges: 'জলবায়ু পরিসীমা',
    averageTemp: 'গড় তাপমাত্রা',
    moistureAverage: 'আর্দ্রতা গড়',
    precipitation: 'বর্ষণ',
    dominantHarvestSeason: 'প্রভাবশালী ফসল ঋতু',
    aiPredictiveConsistency: 'এআই ভবিষ্যদ্বাণীমূলক সামঞ্জস্য',
    evaluatedAcross: 'জুড়ে মূল্যায়ন',
    chartProfile: 'চার্ট প্রোফাইল',
    predictionHistoricalTimeline: 'ভবিষ্যদ্বাণী ঐতিহাসিক টাইমলাইন',
    realTimeChronoTimeline: 'রিয়েল-টাইম ক্রনো টাইমলাইন',
    nitrogenAvg: 'নাইট্রোজেন গড়',
    phosphorusAvg: 'ফসফরাস গড়',
    potassiumAvg: 'পটাসিয়াম গড়',
    sensorDiagnostic: 'সেন্সর ডায়াগনস্টিক',
    macronutrientBalance: 'ম্যাক্রোনিউট্রিয়েন্ট ব্যালেন্স',
    optimalSoilType: 'সর্বোত্তম মাটির ধরন',
    diagnosticRiskProfile: 'ডায়াগনস্টিক রিস্ক প্রোফাইল',
    extremePHWarning: 'সতর্কতা: চরম pH প্রোফাইল সনাক্ত করা হয়েছে',
    phAlkalinityOptimum: 'pH ক্ষারত্ব সূচক সর্বোত্তম',
    basedOnPHCalculations: 'পিএইচ স্তরের গড় গণনার উপর ভিত্তি করে।',
    npkHeatmapIndex: 'NPK হিটম্যাপ সূচক',
    macronutrientAllocationMatrix: 'ম্যাক্রোনিউট্রিয়েন্ট অ্যালোকেশন ম্যাট্রিক্স',
    allocatedIndicesNotice: '*বরাদ্দ সূচক অনুক্রমিক ভবিষ্যদ্বাণী চক্র জুড়ে নিষ্কাশিত আপেক্ষিক রাসায়নিক অনুপাত উপস্থাপন করে।',
    dynamicAIInsights: 'ডায়নামিক এআই অন্তর্দৃষ্টি',
    aiInsightsVerified: 'AgroXAI জ্ঞানীয় অপারেশন যাচাই করা হয়েছে',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    soilHealthOverview: 'মাটি স্বাস্থ্য ওভারভিউ',
    precisionAnalysisHistory: 'যথার্থ বিশ্লেষণ ইতিহাস',
    muskmelon: 'Muskmelon',
    chickpea: 'ছোলা',
    rice: 'ভাত',
    cotton: 'তুলা',
    wheat: 'গম',
    insight1Detail: 'ঐতিহাসিক ভবিষ্যদ্বাণী মৃত্তিকা প্রোফাইল সূচকে উচ্চ এনজাইমেটিক সামঞ্জস্য নিশ্চিত করে।',
    insight2GrowthDetail: 'ফলিয়ার ভলিউম বেঞ্চমার্ক চমৎকার নাইট্রোজেন শোষণ সহগ দেখায়।',
    insight2WarningDetail: 'ম্যাক্রোনিউট্রিয়েন্টের ঘাটতি মূল সালোকসংশ্লেষিত আউটপুট বেগকে সীমিত করে।',
    insight3Detail: 'জলবায়ু টেলিমেট্রি ভেক্টরগুলি ঋতুকালীন আর্দ্রতার পরিসরে পুরোপুরি ফিট করে।',
  },
  te: {
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    selectSubtitle: 'మీకు ఇష్టమైన భాషలో సమాచారం పొందడానికి ఒక భాషను ఎంచుకోండి',
    continueBtn: 'కొనసాగించు',
    searchPlaceholder: 'భాష వెతకండి...',
    changeLanguage: 'భాష మార్చండి',
    navHome: 'హోమ్',
    navRecommend: 'సిఫార్సు',
    navHistory: 'చరిత్ర',
    navMyFarm: 'నా పొలం',
    myFarmTitle: 'నా పొలం',
    myFarmSubtitle: 'మీ ఫీల్డ్‌లను నిర్వహించండి, మీ మట్టిని ట్రాక్ చేయండి మరియు ప్రతి సీజన్‌లో తెలివిగా ప్లాన్ చేయండి.',
    claySoil: 'బంకమట్టి',
    sandySoil: 'ఇసుక నేల',
    loamySoil: 'లోమీ నేల',
    blackSoil: 'నల్ల రేగడి నేల',
    redSoil: 'ఎర్ర నేల',
    alluvialSoil: 'ఒండ్రు నేల',
    saveFieldBtn: 'ఫీల్డ్ సేవ్ చేయండి',
    logCropBtn: 'పంటను లాగ్ చేయండి',
    addNewField: '+ కొత్త ఫీల్డ్‌ని జోడించండి',
    logPastCrop: 'పాత పంటను లాగ్ చేయండి',
    myFieldsHeader: 'నా పొలాలు',
    farmOverviewHeader: 'ఫామ్ అవలోకనం',
    totalFieldsLabel: 'మొత్తం పొలాలు',
    totalAcresLabel: 'మొత్తం ఎకరాలు',
    soilTypesLabel: 'మట్టి రకాలు',
    mostUsedLabel: 'ఎక్కువగా ఉపయోగించినవి',
    cropHistoryHeader: 'పంట చరిత్ర',
    quickInsightsHeader: 'త్వరిత అంతర్దృష్టులు',
    analyzeBtn: 'విశ్లేషించండి',
    kharif: 'ఖరీఫ్',
    rabi: 'రబీ',
    zaid: 'జైద్',
    goodYield: 'మంచి దిగుబడి',
    averageYield: 'సగటు',
    poorYield: 'తక్కువ',
    welcomeBack: 'తిరిగి స్వాగతం',
    loginTitle: 'లాగిన్',
    username: 'వినియోగదారు పేరు',
    password: 'పాస్వర్డ్',
    loginBtn: 'లాగిన్ చేయండి',
    noAccount: 'ఖాతా లేదా?',
    signUp: 'సైన్ అప్',
    logout: 'లాగ్ అవుట్',
    allLanguages: 'అన్ని భాషలు',
    navIntelligence: 'ఇంటెలిజెన్స్',
    addField: 'ఫీల్డ్ జోడించండి',
    runAnalysis: 'విశ్లేషణను అమలు చేయండి',
    viewHistory: 'చరిత్రను వీక్షించండి',
    activeCropsLabel: 'క్రియాశీల పంటలు',
    cropRecordsLabel: 'క్రాప్ రికార్డ్స్',
    riskLevelLabel: 'ప్రమాద స్థాయి',
    successRate: 'విజయం రేటు',
    farmIntelligenceSystem: 'ఫార్మ్ ఇంటెలిజెన్స్ సిస్టమ్',
    cropIntelligence: 'క్రాప్ ఇంటెలిజెన్స్',
    cropIntelligenceSubtitle: 'మీ హిస్టారికల్ ప్రిడిక్షన్ లాగ్‌లను ప్రిడిక్టివ్ అనలిటిక్స్‌గా మారుస్తోంది. ఆపరేటింగ్ సిస్టమ్‌ను టైలర్డ్ క్రాప్ డయాగ్నస్టిక్స్ డ్యాష్‌బోర్డ్‌గా మార్ఫ్ చేయడానికి దిగువ ఏదైనా క్రాప్‌ని ఎంచుకోండి.',
    syncAtlasData: 'అట్లాస్ డేటాను సమకాలీకరించండి',
    noAnalyticsFootprint: 'Analytics పాదముద్ర కనుగొనబడలేదు',
    noAnalyticsFootprintSubtitle: 'ఈ విశ్లేషణ కేంద్రం మీ సిఫార్సు లాగ్‌ల నుండి డైనమిక్‌గా క్రాప్ గణాంకాలను సంకలనం చేస్తుంది. ఈ నాడీ విడ్జెట్‌లను బూట్ చేయడానికి మట్టి నిర్ధారణ సిఫార్సును అమలు చేయండి!',
    generateFirstRecommendation: 'మొదటి సిఫార్సును రూపొందించండి',
    selectLoggedCropProfile: 'లాగిన్ చేసిన క్రాప్ ప్రొఫైల్‌ని ఎంచుకోండి',
    metricMatrix: 'మెట్రిక్ మ్యాట్రిక్స్',
    climaticRanges: 'వాతావరణ పరిధులు',
    averageTemp: 'సగటు ఉష్ణోగ్రత',
    moistureAverage: 'తేమ సగటు',
    precipitation: 'అవపాతం',
    dominantHarvestSeason: 'డామినెంట్ హార్వెస్ట్ సీజన్',
    aiPredictiveConsistency: 'AI ప్రిడిక్టివ్ కన్సిస్టెన్సీ',
    evaluatedAcross: 'అంతటా మూల్యాంకనం చేయబడింది',
    chartProfile: 'చార్ట్ ప్రొఫైల్',
    predictionHistoricalTimeline: 'ప్రిడిక్షన్ హిస్టారికల్ టైమ్‌లైన్',
    realTimeChronoTimeline: 'నిజ-సమయ క్రోనో కాలక్రమం',
    nitrogenAvg: 'నైట్రోజన్ సగటు',
    phosphorusAvg: 'భాస్వరం సగటు',
    potassiumAvg: 'పొటాషియం సగటు',
    sensorDiagnostic: 'సెన్సార్ డయాగ్నోస్టిక్',
    macronutrientBalance: 'మాక్రోన్యూట్రియంట్ బ్యాలెన్స్',
    optimalSoilType: 'ఆప్టిమల్ నేల రకం',
    diagnosticRiskProfile: 'డయాగ్నోస్టిక్ రిస్క్ ప్రొఫైల్',
    extremePHWarning: 'హెచ్చరిక: విపరీతమైన pH ప్రొఫైల్ కనుగొనబడింది',
    phAlkalinityOptimum: 'pH ఆల్కలీనిటీ ఇండెక్స్ వాంఛనీయమైనది',
    basedOnPHCalculations: 'సగటు pH స్థాయి లెక్కల ఆధారంగా.',
    npkHeatmapIndex: 'NPK హీట్‌మ్యాప్ సూచిక',
    macronutrientAllocationMatrix: 'మాక్రోన్యూట్రియెంట్ కేటాయింపు మాతృక',
    allocatedIndicesNotice: '*కేటాయించిన సూచికలు సీక్వెన్షియల్ ప్రిడిక్షన్ సైకిల్స్‌లో సేకరించిన సాపేక్ష రసాయన నిష్పత్తులను సూచిస్తాయి.',
    dynamicAIInsights: 'డైనమిక్ AI అంతర్దృష్టులు',
    aiInsightsVerified: 'AgroXAI కాగ్నిటివ్ కార్యకలాపాలు ధృవీకరించబడ్డాయి',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    soilHealthOverview: 'నేల ఆరోగ్య అవలోకనం',
    precisionAnalysisHistory: 'ఖచ్చితమైన విశ్లేషణ చరిత్ర',
    muskmelon: 'సీతాఫలం',
    chickpea: 'చిక్పీ',
    rice: 'అన్నం',
    cotton: 'పత్తి',
    wheat: 'గోధుమలు',
    insight1Detail: 'మట్టి ప్రొఫైల్ సూచికలలో అధిక ఎంజైమాటిక్ అనుకూలతను చారిత్రక అంచనాలు నిర్ధారిస్తాయి.',
    insight2GrowthDetail: 'ఫోలియర్ వాల్యూమ్ బెంచ్‌మార్క్‌లు అద్భుతమైన నైట్రోజన్ శోషణ గుణకాలను చూపుతాయి.',
    insight2WarningDetail: 'మాక్రోన్యూట్రియెంట్ లోపాలు కోర్ కిరణజన్య సంయోగక్రియ అవుట్‌పుట్ వేగాలను పరిమితం చేస్తాయి.',
    insight3Detail: 'క్లైమాటిక్ టెలిమెట్రీ వెక్టర్స్ కాలానుగుణ తేమ పరిధికి సరిగ్గా సరిపోతాయి.',
  },
  mr: {
    selectLanguage: 'तुमची भाषा निवडा',
    selectSubtitle: 'तुमच्या आवडत्या भाषेत माहिती मिळविण्यासाठी भाषा निवडा',
    continueBtn: 'पुढे जा',
    searchPlaceholder: 'भाषा शोधा...',
    changeLanguage: 'भाषा बदला',
    navHome: 'मुखपृष्ठ',
    navRecommend: 'शिफारस',
    navHistory: 'इतिहास',
    welcomeBack: 'परत स्वागत आहे',
    loginTitle: 'लॉगिन',
    username: 'वापरकर्तानाव',
    password: 'पासवर्ड',
    loginBtn: 'लॉगिन करा',
    noAccount: 'खाते नाही?',
    signUp: 'साइन अप करा',
    logout: 'लॉग आउट',
    allLanguages: 'सर्व भाषा',
    navMyFarm: 'माझे शेत',
    navIntelligence: 'बुद्धिमत्ता',
    myFarmTitle: 'माझे शेत',
    myFarmSubtitle: 'तुमची फील्ड व्यवस्थापित करा, तुमच्या मातीचा मागोवा घ्या आणि प्रत्येक हंगामात अधिक चाणाक्षपणे नियोजन करा.',
    claySoil: 'चिकणमाती माती',
    sandySoil: 'वालुकामय माती',
    loamySoil: 'चिकणमाती माती',
    blackSoil: 'काळी माती',
    redSoil: 'लाल माती',
    alluvialSoil: 'गाळाची माती',
    saveFieldBtn: 'फील्ड जतन करा',
    logCropBtn: 'लॉग क्रॉप',
    addNewField: '+ नवीन फील्ड जोडा',
    logPastCrop: 'लॉग पास्ट क्रॉप',
    myFieldsHeader: 'माझी फील्ड',
    farmOverviewHeader: 'फार्म विहंगावलोकन',
    totalFieldsLabel: 'एकूण फील्ड',
    totalAcresLabel: 'एकूण एकर',
    soilTypesLabel: 'मातीचे प्रकार',
    mostUsedLabel: 'सर्वाधिक वापरले',
    cropHistoryHeader: 'क्रॉप इतिहास',
    quickInsightsHeader: 'द्रुत अंतर्दृष्टी',
    analyzeBtn: 'विश्लेषण करा',
    kharif: 'खरीप',
    rabi: 'रबी',
    zaid: 'झैद',
    goodYield: 'चांगले उत्पन्न',
    averageYield: 'सरासरी',
    poorYield: 'गरीब',
    addField: 'फील्ड जोडा',
    runAnalysis: 'विश्लेषण चालवा',
    viewHistory: 'इतिहास पहा',
    activeCropsLabel: 'सक्रिय पिके',
    cropRecordsLabel: 'पीक नोंदी',
    riskLevelLabel: 'जोखीम पातळी',
    successRate: 'यशाचा दर',
    farmIntelligenceSystem: 'फार्म इंटेलिजेंस सिस्टम',
    cropIntelligence: 'पीक बुद्धिमत्ता',
    cropIntelligenceSubtitle: 'तुमच्या ऐतिहासिक अंदाज नोंदींचे भविष्यसूचक विश्लेषणामध्ये रूपांतर करणे. ऑपरेटिंग सिस्टमला अनुरूप क्रॉप डायग्नोस्टिक्स डॅशबोर्डमध्ये रूपांतरित करण्यासाठी खालील कोणतेही पीक निवडा.',
    syncAtlasData: 'ऍटलस डेटा समक्रमित करा',
    noAnalyticsFootprint: 'कोणतेही Analytics फूटप्रिंट आढळले नाहीत',
    noAnalyticsFootprintSubtitle: 'हे विश्लेषण केंद्र तुमच्या शिफारसी लॉगमधून क्रॉपची आकडेवारी डायनॅमिकपणे संकलित करते. हे न्यूरल विजेट्स बूट करण्यासाठी माती निदान शिफारस करा!',
    generateFirstRecommendation: 'प्रथम शिफारस व्युत्पन्न करा',
    selectLoggedCropProfile: 'लॉग केलेले क्रॉप प्रोफाइल निवडा',
    metricMatrix: 'मेट्रिक मॅट्रिक्स',
    climaticRanges: 'हवामान श्रेणी',
    averageTemp: 'सरासरी तापमान',
    moistureAverage: 'आर्द्रता सरासरी',
    precipitation: 'वर्षाव',
    dominantHarvestSeason: 'प्रबळ कापणीचा हंगाम',
    aiPredictiveConsistency: 'AI अंदाज सुसंगतता',
    evaluatedAcross: 'ओलांडून मूल्यमापन केले',
    chartProfile: 'चार्ट प्रोफाइल',
    predictionHistoricalTimeline: 'अंदाज ऐतिहासिक टाइमलाइन',
    realTimeChronoTimeline: 'रिअल-टाइम क्रोनो टाइमलाइन',
    nitrogenAvg: 'नायट्रोजन सरासरी',
    phosphorusAvg: 'फॉस्फरस सरासरी',
    potassiumAvg: 'पोटॅशियम सरासरी',
    sensorDiagnostic: 'सेन्सर डायग्नोस्टिक',
    macronutrientBalance: 'मॅक्रोन्युट्रिएंट शिल्लक',
    optimalSoilType: 'इष्टतम माती प्रकार',
    diagnosticRiskProfile: 'डायग्नोस्टिक रिस्क प्रोफाइल',
    extremePHWarning: 'चेतावणी: अत्यंत पीएच प्रोफाइल आढळले',
    phAlkalinityOptimum: 'pH क्षारता निर्देशांक इष्टतम',
    basedOnPHCalculations: 'सरासरी पीएच पातळीच्या गणनेवर आधारित.',
    npkHeatmapIndex: 'NPK हीटमॅप इंडेक्स',
    macronutrientAllocationMatrix: 'मॅक्रोन्युट्रिएंट ऍलोकेशन मॅट्रिक्स',
    allocatedIndicesNotice: '*वाटप केलेले निर्देशांक अनुक्रमिक अंदाज चक्रांमध्ये काढलेल्या सापेक्ष रासायनिक प्रमाणांचे प्रतिनिधित्व करतात.',
    dynamicAIInsights: 'डायनॅमिक एआय अंतर्दृष्टी',
    aiInsightsVerified: 'AgroXAI संज्ञानात्मक ऑपरेशन्स सत्यापित',
    recentActivity: 'अलीकडील क्रियाकलाप',
    soilHealthOverview: 'माती आरोग्य विहंगावलोकन',
    precisionAnalysisHistory: 'अचूक विश्लेषण इतिहास',
    muskmelon: 'कस्तुरी',
    chickpea: 'चणे',
    rice: 'तांदूळ',
    cotton: 'कापूस',
    wheat: 'गहू',
    insight1Detail: 'ऐतिहासिक अंदाज माती प्रोफाइल निर्देशांकांमध्ये उच्च एंजाइमॅटिक सुसंगततेची पुष्टी करतात.',
    insight2GrowthDetail: 'फॉलीअर व्हॉल्यूम बेंचमार्क उत्कृष्ट नायट्रोजन शोषण गुणांक दर्शवतात.',
    insight2WarningDetail: 'मॅक्रोन्युट्रिएंटची कमतरता कोर प्रकाशसंश्लेषण आउटपुट वेग मर्यादित करते.',
    insight3Detail: 'हवामानातील टेलीमेट्री वेक्टर्स हंगामी आर्द्रता श्रेणीमध्ये उत्तम प्रकारे बसतात.',
  },
  ta: {
    selectLanguage: 'உங்கள் மொழியை தேர்ந்தெடுங்கள்',
    selectSubtitle: 'உங்கள் விருப்பமான மொழியில் தகவல்களைப் பெற ஒரு மொழியைத் தேர்ந்தெடுங்கள்',
    continueBtn: 'தொடரவும்',
    searchPlaceholder: 'மொழி தேடுங்கள்...',
    changeLanguage: 'மொழி மாற்றுங்கள்',
    navHome: 'முகப்பு',
    navRecommend: 'பரிந்துரை',
    navHistory: 'வரலாறு',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    loginTitle: 'உள்நுழைவு',
    username: 'பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    loginBtn: 'உள்நுழைக',
    noAccount: 'கணக்கு இல்லையா?',
    signUp: 'பதிவு செய்க',
    logout: 'வெளியேறு',
    allLanguages: 'அனைத்து மொழிகள்',
    navMyFarm: 'என் பண்ணை',
    navIntelligence: 'உளவுத்துறை',
    myFarmTitle: 'என் பண்ணை',
    myFarmSubtitle: 'உங்கள் வயல்களை நிர்வகிக்கவும், உங்கள் மண்ணைக் கண்காணிக்கவும் மற்றும் ஒவ்வொரு பருவத்திலும் சிறந்த முறையில் திட்டமிடவும்.',
    claySoil: 'களிமண் மண்',
    sandySoil: 'மணல் மண்',
    loamySoil: 'களிமண் மண்',
    blackSoil: 'கருப்பு மண்',
    redSoil: 'சிவப்பு மண்',
    alluvialSoil: 'வண்டல் மண்',
    saveFieldBtn: 'களத்தைச் சேமி',
    logCropBtn: 'பதிவு பயிர்',
    addNewField: '+ புதிய புலத்தைச் சேர்க்கவும்',
    logPastCrop: 'பதிவு கடந்த பயிர்',
    myFieldsHeader: 'என் புலங்கள்',
    farmOverviewHeader: 'பண்ணை கண்ணோட்டம்',
    totalFieldsLabel: 'மொத்த புலங்கள்',
    totalAcresLabel: 'மொத்த ஏக்கர்',
    soilTypesLabel: 'மண் வகைகள்',
    mostUsedLabel: 'அதிகம் பயன்படுத்தப்பட்டது',
    cropHistoryHeader: 'பயிர் வரலாறு',
    quickInsightsHeader: 'விரைவான நுண்ணறிவு',
    analyzeBtn: 'பகுப்பாய்வு செய்யவும்',
    kharif: 'காரீஃப்',
    rabi: 'ரபி',
    zaid: 'ஜைத்',
    goodYield: 'நல்ல மகசூல்',
    averageYield: 'சராசரி',
    poorYield: 'ஏழை',
    addField: 'புலத்தைச் சேர்க்கவும்',
    runAnalysis: 'பகுப்பாய்வு இயக்கவும்',
    viewHistory: 'வரலாற்றைக் காண்க',
    activeCropsLabel: 'செயலில் உள்ள பயிர்கள்',
    cropRecordsLabel: 'பயிர் பதிவுகள்',
    riskLevelLabel: 'இடர் நிலை',
    successRate: 'வெற்றி விகிதம்',
    farmIntelligenceSystem: 'பண்ணை நுண்ணறிவு அமைப்பு',
    cropIntelligence: 'பயிர் நுண்ணறிவு',
    cropIntelligenceSubtitle: 'உங்கள் வரலாற்று கணிப்புப் பதிவுகளை முன்கணிப்பு பகுப்பாய்வுகளாக மாற்றுதல். ஆப்பரேட்டிங் சிஸ்டத்தை வடிவமைக்கப்பட்ட பயிர் கண்டறிதல் டாஷ்போர்டாக மாற்றுவதற்கு கீழே உள்ள எந்தப் பயிர்களையும் தேர்ந்தெடுக்கவும்.',
    syncAtlasData: 'அட்லஸ் தரவை ஒத்திசைக்கவும்',
    noAnalyticsFootprint: 'Analytics தடம் எதுவும் கிடைக்கவில்லை',
    noAnalyticsFootprintSubtitle: 'இந்த பகுப்பாய்வு மையம் உங்கள் பரிந்துரைப் பதிவுகளிலிருந்து மாறும் வகையில் பயிர் புள்ளிவிவரங்களைத் தொகுக்கிறது. இந்த நரம்பியல் விட்ஜெட்களை துவக்க மண் கண்டறியும் பரிந்துரையை செய்யவும்!',
    generateFirstRecommendation: 'முதல் பரிந்துரையை உருவாக்கவும்',
    selectLoggedCropProfile: 'உள்நுழைந்த கிராப் சுயவிவரத்தைத் தேர்ந்தெடுக்கவும்',
    metricMatrix: 'மெட்ரிக் மேட்ரிக்ஸ்',
    climaticRanges: 'காலநிலை வரம்புகள்',
    averageTemp: 'சராசரி வெப்பநிலை',
    moistureAverage: 'ஈரப்பதம் சராசரி',
    precipitation: 'மழைப்பொழிவு',
    dominantHarvestSeason: 'ஆதிக்கம் செலுத்தும் அறுவடை சீசன்',
    aiPredictiveConsistency: 'AI முன்கணிப்பு நிலைத்தன்மை',
    evaluatedAcross: 'முழுவதும் மதிப்பிடப்பட்டது',
    chartProfile: 'விளக்கப்படம் சுயவிவரம்',
    predictionHistoricalTimeline: 'கணிப்பு வரலாற்று காலவரிசை',
    realTimeChronoTimeline: 'நிகழ்நேர க்ரோனோ காலவரிசை',
    nitrogenAvg: 'நைட்ரஜன் சராசரி',
    phosphorusAvg: 'பாஸ்பரஸ் சராசரி',
    potassiumAvg: 'பொட்டாசியம் சராசரி',
    sensorDiagnostic: 'சென்சார் கண்டறிதல்',
    macronutrientBalance: 'மக்ரோனூட்ரியண்ட் பேலன்ஸ்',
    optimalSoilType: 'உகந்த மண் வகை',
    diagnosticRiskProfile: 'கண்டறியும் ஆபத்து சுயவிவரம்',
    extremePHWarning: 'எச்சரிக்கை: தீவிர pH சுயவிவரம் கண்டறியப்பட்டது',
    phAlkalinityOptimum: 'pH காரத்தன்மை இன்டெக்ஸ் உகந்தது',
    basedOnPHCalculations: 'சராசரி pH நிலை கணக்கீடுகளின் அடிப்படையில்.',
    npkHeatmapIndex: 'NPK ஹீட்மேப் இன்டெக்ஸ்',
    macronutrientAllocationMatrix: 'மக்ரோனூட்ரியன்ட் அலோகேஷன் மேட்ரிக்ஸ்',
    allocatedIndicesNotice: '*ஒதுக்கப்பட்ட குறியீடுகள் தொடர் கணிப்பு சுழற்சிகளில் பிரித்தெடுக்கப்பட்ட ஒப்பீட்டு இரசாயன விகிதங்களைக் குறிக்கின்றன.',
    dynamicAIInsights: 'டைனமிக் ஏஐ நுண்ணறிவு',
    aiInsightsVerified: 'AgroXAI அறிவாற்றல் செயல்பாடுகள் சரிபார்க்கப்பட்டது',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    soilHealthOverview: 'மண் ஆரோக்கிய கண்ணோட்டம்',
    precisionAnalysisHistory: 'துல்லியமான பகுப்பாய்வு வரலாறு',
    muskmelon: 'முலாம்பழம்',
    chickpea: 'கொண்டைக்கடலை',
    rice: 'அரிசி',
    cotton: 'பருத்தி',
    wheat: 'கோதுமை',
    insight1Detail: 'வரலாற்றுக் கணிப்புகள் மண் விவரக் குறியீடுகளில் அதிக நொதிப் பொருந்தக்கூடிய தன்மையை உறுதிப்படுத்துகின்றன.',
    insight2GrowthDetail: 'ஃபோலியார் தொகுதி வரையறைகள் சிறந்த நைட்ரஜன் உறிஞ்சுதல் குணகங்களைக் காட்டுகின்றன.',
    insight2WarningDetail: 'மக்ரோநியூட்ரியண்ட் குறைபாடுகள் முக்கிய ஒளிச்சேர்க்கை வெளியீட்டு வேகத்தை கட்டுப்படுத்துகின்றன.',
    insight3Detail: 'காலநிலை டெலிமெட்ரி திசையன்கள் பருவகால ஈரப்பதம் வரம்பிற்கு கச்சிதமாக பொருந்துகின்றன.',
  },
  gu: {
    selectLanguage: 'તમારી ભાષા પસંદ કરો',
    selectSubtitle: 'તમારી પસંદની ભાષામાં માહિતી મેળવવા ભાષા પસંદ કરો',
    continueBtn: 'આગળ વધો',
    searchPlaceholder: 'ભાષા શોધો...',
    changeLanguage: 'ભાષા બદલો',
    navHome: 'હોમ',
    navRecommend: 'ભલામણ',
    navHistory: 'ઇતિહાસ',
    welcomeBack: 'પાછા સ્વાગત છે',
    loginTitle: 'લૉગિન',
    username: 'વપરાશકર્તાનું નામ',
    password: 'પાસવર્ડ',
    loginBtn: 'લૉગિન કરો',
    noAccount: 'ખાતું નથી?',
    signUp: 'સાઇન અપ',
    logout: 'લૉગ આઉટ',
    allLanguages: 'બધી ભાષાઓ',
    navMyFarm: 'માય ફાર્મ',
    navIntelligence: 'બુદ્ધિ',
    myFarmTitle: 'મારું ફાર્મ',
    myFarmSubtitle: 'તમારા ક્ષેત્રોનું સંચાલન કરો, તમારી જમીનને ટ્રૅક કરો અને દરેક સિઝનમાં વધુ સ્માર્ટ પ્લાન કરો.',
    claySoil: 'માટીની માટી',
    sandySoil: 'રેતાળ માટી',
    loamySoil: 'લોમી માટી',
    blackSoil: 'કાળી માટી',
    redSoil: 'લાલ માટી',
    alluvialSoil: 'કાંપવાળી માટી',
    saveFieldBtn: 'ક્ષેત્ર સાચવો',
    logCropBtn: 'લોગ પાક',
    addNewField: '+ નવું ક્ષેત્ર ઉમેરો',
    logPastCrop: 'લૉગ પાસ્ટ ક્રોપ',
    myFieldsHeader: 'મારા ક્ષેત્રો',
    farmOverviewHeader: 'ફાર્મ વિહંગાવલોકન',
    totalFieldsLabel: 'કુલ ક્ષેત્રો',
    totalAcresLabel: 'કુલ એકર',
    soilTypesLabel: 'માટીના પ્રકાર',
    mostUsedLabel: 'સૌથી વધુ ઉપયોગમાં લેવાય છે',
    cropHistoryHeader: 'પાકનો ઇતિહાસ',
    quickInsightsHeader: 'ઝડપી આંતરદૃષ્ટિ',
    analyzeBtn: 'વિશ્લેષણ કરો',
    kharif: 'ખરીફ',
    rabi: 'રબી',
    zaid: 'ઝૈદ',
    goodYield: 'સારી ઉપજ',
    averageYield: 'સરેરાશ',
    poorYield: 'ગરીબ',
    addField: 'ક્ષેત્ર ઉમેરો',
    runAnalysis: 'વિશ્લેષણ ચલાવો',
    viewHistory: 'ઇતિહાસ જુઓ',
    activeCropsLabel: 'સક્રિય પાક',
    cropRecordsLabel: 'પાક રેકોર્ડ',
    riskLevelLabel: 'જોખમ સ્તર',
    successRate: 'સફળતા દર',
    farmIntelligenceSystem: 'ફાર્મ ઇન્ટેલિજન્સ સિસ્ટમ',
    cropIntelligence: 'પાક બુદ્ધિ',
    cropIntelligenceSubtitle: 'તમારા ઐતિહાસિક અનુમાન લૉગને અનુમાનિત વિશ્લેષણમાં રૂપાંતરિત કરવું. ઓપરેટિંગ સિસ્ટમને અનુરૂપ ક્રોપ ડાયગ્નોસ્ટિક્સ ડેશબોર્ડમાં મોર્ફ કરવા માટે નીચેનો કોઈપણ પાક પસંદ કરો.',
    syncAtlasData: 'એટલાસ ડેટાને સમન્વયિત કરો',
    noAnalyticsFootprint: 'કોઈ Analytics ફૂટપ્રિન્ટ મળી નથી',
    noAnalyticsFootprintSubtitle: 'આ વિશ્લેષણ કેન્દ્ર તમારા ભલામણ લૉગમાંથી ગતિશીલ રીતે પાકના આંકડાઓનું સંકલન કરે છે. આ ન્યુરલ વિજેટ્સને બુટ કરવા માટે માટી ડાયગ્નોસ્ટિક ભલામણ કરો!',
    generateFirstRecommendation: 'પ્રથમ ભલામણ જનરેટ કરો',
    selectLoggedCropProfile: 'લૉગ કરેલ ક્રોપ પ્રોફાઇલ પસંદ કરો',
    metricMatrix: 'મેટ્રિક મેટ્રિક્સ',
    climaticRanges: 'આબોહવાની શ્રેણીઓ',
    averageTemp: 'સરેરાશ તાપમાન',
    moistureAverage: 'ભેજ સરેરાશ',
    precipitation: 'વરસાદ',
    dominantHarvestSeason: 'પ્રબળ હાર્વેસ્ટ સિઝન',
    aiPredictiveConsistency: 'AI આગાહી સુસંગતતા',
    evaluatedAcross: 'સમગ્ર મૂલ્યાંકન કર્યું',
    chartProfile: 'ચાર્ટ પ્રોફાઇલ',
    predictionHistoricalTimeline: 'આગાહી ઐતિહાસિક સમયરેખા',
    realTimeChronoTimeline: 'રીઅલ-ટાઇમ ક્રોનો સમયરેખા',
    nitrogenAvg: 'નાઇટ્રોજન સરેરાશ',
    phosphorusAvg: 'ફોસ્ફરસ સરેરાશ',
    potassiumAvg: 'પોટેશિયમ સરેરાશ',
    sensorDiagnostic: 'સેન્સર ડાયગ્નોસ્ટિક',
    macronutrientBalance: 'મેક્રોન્યુટ્રિએન્ટ બેલેન્સ',
    optimalSoilType: 'શ્રેષ્ઠ માટીનો પ્રકાર',
    diagnosticRiskProfile: 'ડાયગ્નોસ્ટિક રિસ્ક પ્રોફાઇલ',
    extremePHWarning: 'ચેતવણી: એક્સ્ટ્રીમ pH પ્રોફાઇલ મળી',
    phAlkalinityOptimum: 'પીએચ આલ્કલિનિટી ઇન્ડેક્સ શ્રેષ્ઠ',
    basedOnPHCalculations: 'સરેરાશ pH સ્તરની ગણતરીઓ પર આધારિત.',
    npkHeatmapIndex: 'NPK હીટમેપ ઇન્ડેક્સ',
    macronutrientAllocationMatrix: 'મેક્રોન્યુટ્રિએન્ટ ફાળવણી મેટ્રિક્સ',
    allocatedIndicesNotice: '*ફાળવેલ સૂચકાંકો અનુક્રમિક આગાહી ચક્રમાં કાઢવામાં આવેલા સાપેક્ષ રાસાયણિક પ્રમાણને રજૂ કરે છે.',
    dynamicAIInsights: 'ડાયનેમિક એઆઈ ઈન્સાઈટ્સ',
    aiInsightsVerified: 'AgroXAI જ્ઞાનાત્મક કામગીરી ચકાસાયેલ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    soilHealthOverview: 'માટી આરોગ્ય ઝાંખી',
    precisionAnalysisHistory: 'ચોકસાઇ વિશ્લેષણ ઇતિહાસ',
    muskmelon: 'મસ્કમેલન',
    chickpea: 'ચણા',
    rice: 'ચોખા',
    cotton: 'કપાસ',
    wheat: 'ઘઉં',
    insight1Detail: 'ઐતિહાસિક આગાહીઓ માટી પ્રોફાઇલ સૂચકાંકોમાં ઉચ્ચ એન્ઝાઇમેટિક સુસંગતતાની પુષ્ટિ કરે છે.',
    insight2GrowthDetail: 'ફોલિઅર વોલ્યુમ બેન્ચમાર્ક ઉત્તમ નાઇટ્રોજન શોષણ ગુણાંક દર્શાવે છે.',
    insight2WarningDetail: 'મેક્રોન્યુટ્રિઅન્ટની ઉણપ કોર પ્રકાશસંશ્લેષણ આઉટપુટ વેગને મર્યાદિત કરે છે.',
    insight3Detail: 'ક્લાઇમેટિક ટેલિમેટ્રી વેક્ટર મોસમી ભેજની શ્રેણીમાં સંપૂર્ણ રીતે ફિટ છે.',
  },
  kn: {
    selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    selectSubtitle: 'ನಿಮಗೆ ಇಷ್ಟವಾದ ಭಾಷೆಯಲ್ಲಿ ಮಾಹಿತಿ ಪಡೆಯಲು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    continueBtn: 'ಮುಂದುವರಿಯಿರಿ',
    searchPlaceholder: 'ಭಾಷೆ ಹುಡುಕಿ...',
    changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
    navHome: 'ಮನೆ',
    navRecommend: 'ಶಿಫಾರಸು',
    navHistory: 'ಇತಿಹಾಸ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗत',
    loginTitle: 'ಲಾಗಿನ್',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್ವರ್ಡ್',
    loginBtn: 'ಲಾಗಿನ್ ಮಾಡಿ',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    signUp: 'ಸೈನ್ ಅಪ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    allLanguages: 'ಎಲ್ಲಾ ಭಾಷೆಗಳು',
    navMyFarm: 'ನನ್ನ ಫಾರ್ಮ್',
    navIntelligence: 'ಗುಪ್ತಚರ',
    myFarmTitle: 'ನನ್ನ ಫಾರ್ಮ್',
    myFarmSubtitle: 'ನಿಮ್ಮ ಕ್ಷೇತ್ರಗಳನ್ನು ನಿರ್ವಹಿಸಿ, ನಿಮ್ಮ ಮಣ್ಣನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಪ್ರತಿ ಕ್ರೀಡಾಋತುವಿನಲ್ಲಿ ಚುರುಕಾಗಿ ಯೋಜಿಸಿ.',
    claySoil: 'ಕ್ಲೇ ಮಣ್ಣು',
    sandySoil: 'ಮರಳು ಮಣ್ಣು',
    loamySoil: 'ಲೋಮಿ ಮಣ್ಣು',
    blackSoil: 'ಕಪ್ಪು ಮಣ್ಣು',
    redSoil: 'ಕೆಂಪು ಮಣ್ಣು',
    alluvialSoil: 'ಮೆಕ್ಕಲು ಮಣ್ಣು',
    saveFieldBtn: 'ಕ್ಷೇತ್ರವನ್ನು ಉಳಿಸಿ',
    logCropBtn: 'ಲಾಗ್ ಕ್ರಾಪ್',
    addNewField: '+ ಹೊಸ ಕ್ಷೇತ್ರವನ್ನು ಸೇರಿಸಿ',
    logPastCrop: 'ಲಾಗ್ ಪಾಸ್ಟ್ ಕ್ರಾಪ್',
    myFieldsHeader: 'ನನ್ನ ಕ್ಷೇತ್ರಗಳು',
    farmOverviewHeader: 'ಫಾರ್ಮ್ ಅವಲೋಕನ',
    totalFieldsLabel: 'ಒಟ್ಟು ಕ್ಷೇತ್ರಗಳು',
    totalAcresLabel: 'ಒಟ್ಟು ಎಕರೆಗಳು',
    soilTypesLabel: 'ಮಣ್ಣಿನ ವಿಧಗಳು',
    mostUsedLabel: 'ಹೆಚ್ಚು ಬಳಸಲಾಗಿದೆ',
    cropHistoryHeader: 'ಬೆಳೆ ಇತಿಹಾಸ',
    quickInsightsHeader: 'ತ್ವರಿತ ಒಳನೋಟಗಳು',
    analyzeBtn: 'ವಿಶ್ಲೇಷಿಸಿ',
    kharif: 'ಖಾರಿಫ್',
    rabi: 'ರಬಿ',
    zaid: 'ಜೈದ್',
    goodYield: 'ಉತ್ತಮ ಇಳುವರಿ',
    averageYield: 'ಸರಾಸರಿ',
    poorYield: 'ಬಡವ',
    addField: 'ಕ್ಷೇತ್ರವನ್ನು ಸೇರಿಸಿ',
    runAnalysis: 'ವಿಶ್ಲೇಷಣೆ ರನ್ ಮಾಡಿ',
    viewHistory: 'ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಿ',
    activeCropsLabel: 'ಸಕ್ರಿಯ ಬೆಳೆಗಳು',
    cropRecordsLabel: 'ಬೆಳೆ ದಾಖಲೆಗಳು',
    riskLevelLabel: 'ಅಪಾಯದ ಮಟ್ಟ',
    successRate: 'ಯಶಸ್ಸಿನ ಪ್ರಮಾಣ',
    farmIntelligenceSystem: 'ಫಾರ್ಮ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಸಿಸ್ಟಮ್',
    cropIntelligence: 'ಕ್ರಾಪ್ ಇಂಟೆಲಿಜೆನ್ಸ್',
    cropIntelligenceSubtitle: 'ನಿಮ್ಮ ಐತಿಹಾಸಿಕ ಭವಿಷ್ಯ ಲಾಗ್‌ಗಳನ್ನು ಮುನ್ಸೂಚಕ ವಿಶ್ಲೇಷಣೆಯಾಗಿ ಪರಿವರ್ತಿಸುವುದು. ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ ಅನ್ನು ಸೂಕ್ತವಾದ ಕ್ರಾಪ್ ಡಯಾಗ್ನೋಸ್ಟಿಕ್ಸ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮಾರ್ಫ್ ಮಾಡಲು ಕೆಳಗಿನ ಯಾವುದೇ ಕ್ರಾಪ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    syncAtlasData: 'ಅಟ್ಲಾಸ್ ಡೇಟಾವನ್ನು ಸಿಂಕ್ ಮಾಡಿ',
    noAnalyticsFootprint: 'ಯಾವುದೇ Analytics ಹೆಜ್ಜೆಗುರುತು ಕಂಡುಬಂದಿಲ್ಲ',
    noAnalyticsFootprintSubtitle: 'ಈ ವಿಶ್ಲೇಷಣಾ ಕೇಂದ್ರವು ನಿಮ್ಮ ಶಿಫಾರಸು ಲಾಗ್‌ಗಳಿಂದ ಕ್ರಿಯಾತ್ಮಕವಾಗಿ ಬೆಳೆ ಅಂಕಿಅಂಶಗಳನ್ನು ಸಂಗ್ರಹಿಸುತ್ತದೆ. ಈ ನರಗಳ ವಿಜೆಟ್‌ಗಳನ್ನು ಬೂಟ್ ಮಾಡಲು ಮಣ್ಣಿನ ರೋಗನಿರ್ಣಯದ ಶಿಫಾರಸನ್ನು ಮಾಡಿ!',
    generateFirstRecommendation: 'ಮೊದಲ ಶಿಫಾರಸು ರಚಿಸಿ',
    selectLoggedCropProfile: 'ಲಾಗ್ ಮಾಡಿದ ಕ್ರಾಪ್ ಪ್ರೊಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    metricMatrix: 'ಮೆಟ್ರಿಕ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    climaticRanges: 'ಹವಾಮಾನ ಶ್ರೇಣಿಗಳು',
    averageTemp: 'ಸರಾಸರಿ ತಾಪಮಾನ',
    moistureAverage: 'ತೇವಾಂಶ ಸರಾಸರಿ',
    precipitation: 'ಮಳೆ',
    dominantHarvestSeason: 'ಡಾಮಿನಾಂಟ್ ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್',
    aiPredictiveConsistency: 'AI ಪ್ರೆಡಿಕ್ಟಿವ್ ಸ್ಥಿರತೆ',
    evaluatedAcross: 'ಅಡ್ಡಲಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗಿದೆ',
    chartProfile: 'ಚಾರ್ಟ್ ಪ್ರೊಫೈಲ್',
    predictionHistoricalTimeline: 'ಪ್ರೆಡಿಕ್ಷನ್ ಐತಿಹಾಸಿಕ ಟೈಮ್‌ಲೈನ್',
    realTimeChronoTimeline: 'ರಿಯಲ್-ಟೈಮ್ ಕ್ರೋನೋ ಟೈಮ್‌ಲೈನ್',
    nitrogenAvg: 'ಸಾರಜನಕ ಸರಾಸರಿ',
    phosphorusAvg: 'ರಂಜಕ ಸರಾಸರಿ',
    potassiumAvg: 'ಪೊಟ್ಯಾಸಿಯಮ್ ಸರಾಸರಿ',
    sensorDiagnostic: 'ಸಂವೇದಕ ಡಯಾಗ್ನೋಸ್ಟಿಕ್',
    macronutrientBalance: 'ಮ್ಯಾಕ್ರೋನ್ಯೂಟ್ರಿಯೆಂಟ್ ಬ್ಯಾಲೆನ್ಸ್',
    optimalSoilType: 'ಆಪ್ಟಿಮಲ್ ಮಣ್ಣಿನ ವಿಧ',
    diagnosticRiskProfile: 'ಡಯಾಗ್ನೋಸ್ಟಿಕ್ ರಿಸ್ಕ್ ಪ್ರೊಫೈಲ್',
    extremePHWarning: 'ಎಚ್ಚರಿಕೆ: ತೀವ್ರ pH ಪ್ರೊಫೈಲ್ ಪತ್ತೆಯಾಗಿದೆ',
    phAlkalinityOptimum: 'pH ಕ್ಷಾರೀಯ ಸೂಚ್ಯಂಕ ಅತ್ಯುತ್ತಮವಾಗಿದೆ',
    basedOnPHCalculations: 'ಸರಾಸರಿ pH ಮಟ್ಟದ ಲೆಕ್ಕಾಚಾರಗಳನ್ನು ಆಧರಿಸಿ.',
    npkHeatmapIndex: 'NPK ಹೀಟ್‌ಮ್ಯಾಪ್ ಸೂಚ್ಯಂಕ',
    macronutrientAllocationMatrix: 'ಮ್ಯಾಕ್ರೋನ್ಯೂಟ್ರಿಯೆಂಟ್ ಅಲೊಕೇಶನ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    allocatedIndicesNotice: '*ನಿಯೋಜಿತ ಸೂಚ್ಯಂಕಗಳು ಅನುಕ್ರಮ ಮುನ್ಸೂಚನೆಯ ಚಕ್ರಗಳಲ್ಲಿ ಹೊರತೆಗೆಯಲಾದ ಸಾಪೇಕ್ಷ ರಾಸಾಯನಿಕ ಅನುಪಾತಗಳನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತವೆ.',
    dynamicAIInsights: 'ಡೈನಾಮಿಕ್ ಎಐ ಒಳನೋಟಗಳು',
    aiInsightsVerified: 'AgroXAI ಅರಿವಿನ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    soilHealthOverview: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯದ ಅವಲೋಕನ',
    precisionAnalysisHistory: 'ನಿಖರವಾದ ವಿಶ್ಲೇಷಣೆಯ ಇತಿಹಾಸ',
    muskmelon: 'ಸೀತಾಫಲ',
    chickpea: 'ಕಡಲೆ',
    rice: 'ಅಕ್ಕಿ',
    cotton: 'ಹತ್ತಿ',
    wheat: 'ಗೋಧಿ',
    insight1Detail: 'ಐತಿಹಾಸಿಕ ಮುನ್ನೋಟಗಳು ಮಣ್ಣಿನ ಪ್ರೊಫೈಲ್ ಸೂಚ್ಯಂಕಗಳಲ್ಲಿ ಹೆಚ್ಚಿನ ಎಂಜೈಮ್ಯಾಟಿಕ್ ಹೊಂದಾಣಿಕೆಯನ್ನು ದೃಢೀಕರಿಸುತ್ತವೆ.',
    insight2GrowthDetail: 'ಎಲೆಗಳ ಪರಿಮಾಣದ ಮಾನದಂಡಗಳು ಅತ್ಯುತ್ತಮ ಸಾರಜನಕ ಹೀರಿಕೊಳ್ಳುವ ಗುಣಾಂಕಗಳನ್ನು ತೋರಿಸುತ್ತವೆ.',
    insight2WarningDetail: 'ಮ್ಯಾಕ್ರೋನ್ಯೂಟ್ರಿಯಂಟ್ ಕೊರತೆಗಳು ಕೋರ್ ದ್ಯುತಿಸಂಶ್ಲೇಷಕ ಔಟ್‌ಪುಟ್ ವೇಗವನ್ನು ಮಿತಿಗೊಳಿಸುತ್ತವೆ.',
    insight3Detail: 'ಹವಾಮಾನ ಟೆಲಿಮೆಟ್ರಿ ವೆಕ್ಟರ್‌ಗಳು ಕಾಲೋಚಿತ ಆರ್ದ್ರತೆಯ ಶ್ರೇಣಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತವೆ.',
  },
  ml: {
    selectLanguage: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    selectSubtitle: 'നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷയിൽ വിവരങ്ങൾ നേടാൻ ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
    continueBtn: 'തുടരുക',
    searchPlaceholder: 'ഭാഷ തിരയുക...',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    navHome: 'ഹോം',
    navRecommend: 'ശുപാർശ',
    navHistory: 'ചരിത്രം',
    welcomeBack: 'തിരിച്ചു സ്വാഗതം',
    loginTitle: 'ലോഗിൻ',
    username: 'ഉപയോക്തൃ നാമം',
    password: 'പാസ്‌വേഡ്',
    loginBtn: 'ലോഗിൻ ചെയ്യുക',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    signUp: 'സൈൻ അപ്',
    logout: 'ലോഗ് ഔട്ട്',
    allLanguages: 'എല്ലാ ഭാഷകളും',
    navMyFarm: 'എൻ്റെ ഫാം',
    navIntelligence: 'ഇൻ്റലിജൻസ്',
    myFarmTitle: 'എൻ്റെ ഫാം',
    myFarmSubtitle: 'നിങ്ങളുടെ ഫീൽഡുകൾ നിയന്ത്രിക്കുക, നിങ്ങളുടെ മണ്ണ് ട്രാക്ക് ചെയ്യുക, എല്ലാ സീസണിലും മികച്ച രീതിയിൽ ആസൂത്രണം ചെയ്യുക.',
    claySoil: 'കളിമൺ മണ്ണ്',
    sandySoil: 'മണൽ മണ്ണ്',
    loamySoil: 'പശിമരാശി മണ്ണ്',
    blackSoil: 'കറുത്ത മണ്ണ്',
    redSoil: 'ചുവന്ന മണ്ണ്',
    alluvialSoil: 'അലുവിയൽ മണ്ണ്',
    saveFieldBtn: 'ഫീൽഡ് സംരക്ഷിക്കുക',
    logCropBtn: 'ലോഗ് ക്രോപ്പ്',
    addNewField: '+ പുതിയ ഫീൽഡ് ചേർക്കുക',
    logPastCrop: 'ലോഗ് പാസ്റ്റ് ക്രോപ്പ്',
    myFieldsHeader: 'എൻ്റെ വയലുകൾ',
    farmOverviewHeader: 'ഫാം അവലോകനം',
    totalFieldsLabel: 'മൊത്തം ഫീൽഡുകൾ',
    totalAcresLabel: 'ആകെ ഏക്കറുകൾ',
    soilTypesLabel: 'മണ്ണിൻ്റെ തരങ്ങൾ',
    mostUsedLabel: 'ഏറ്റവും കൂടുതൽ ഉപയോഗിച്ചത്',
    cropHistoryHeader: 'ക്രോപ്പ് ഹിസ്റ്ററി',
    quickInsightsHeader: 'ദ്രുത സ്ഥിതിവിവരക്കണക്കുകൾ',
    analyzeBtn: 'വിശകലനം ചെയ്യുക',
    kharif: 'ഖാരിഫ്',
    rabi: 'റാബി',
    zaid: 'സെയ്ദ്',
    goodYield: 'നല്ല വിളവ്',
    averageYield: 'ശരാശരി',
    poorYield: 'പാവം',
    addField: 'ഫീൽഡ് ചേർക്കുക',
    runAnalysis: 'വിശകലനം പ്രവർത്തിപ്പിക്കുക',
    viewHistory: 'ചരിത്രം കാണുക',
    activeCropsLabel: 'സജീവ വിളകൾ',
    cropRecordsLabel: 'വിള രേഖകൾ',
    riskLevelLabel: 'റിസ്ക് ലെവൽ',
    successRate: 'വിജയ നിരക്ക്',
    farmIntelligenceSystem: 'ഫാം ഇൻ്റലിജൻസ് സിസ്റ്റം',
    cropIntelligence: 'ക്രോപ്പ് ഇൻ്റലിജൻസ്',
    cropIntelligenceSubtitle: 'നിങ്ങളുടെ ചരിത്രപരമായ പ്രവചന ലോഗുകളെ പ്രവചന വിശകലനത്തിലേക്ക് മാറ്റുന്നു. ക്രോപ്പ് ഡയഗ്നോസ്റ്റിക്സ് ഡാഷ്ബോർഡിലേക്ക് ഓപ്പറേറ്റിംഗ് സിസ്റ്റം മോർഫ് ചെയ്യാൻ താഴെയുള്ള ഏതെങ്കിലും ക്രോപ്പ് തിരഞ്ഞെടുക്കുക.',
    syncAtlasData: 'അറ്റ്ലസ് ഡാറ്റ സമന്വയിപ്പിക്കുക',
    noAnalyticsFootprint: 'Analytics കാൽപ്പാടുകളൊന്നും കണ്ടെത്തിയില്ല',
    noAnalyticsFootprintSubtitle: 'ഈ അനലിറ്റിക്‌സ് സെൻ്റർ നിങ്ങളുടെ ശുപാർശ ലോഗുകളിൽ നിന്ന് ചലനാത്മകമായി ക്രോപ്പ് സ്ഥിതിവിവരക്കണക്കുകൾ സമാഹരിക്കുന്നു. ഈ ന്യൂറൽ വിജറ്റുകൾ ബൂട്ട് ചെയ്യാൻ ഒരു മണ്ണ് ഡയഗ്നോസ്റ്റിക് ശുപാർശ നടത്തുക!',
    generateFirstRecommendation: 'ആദ്യ ശുപാർശ ജനറേറ്റ് ചെയ്യുക',
    selectLoggedCropProfile: 'ലോഗിൻ ചെയ്‌ത ക്രോപ്പ് പ്രൊഫൈൽ തിരഞ്ഞെടുക്കുക',
    metricMatrix: 'മെട്രിക് മെട്രിക്സ്',
    climaticRanges: 'കാലാവസ്ഥാ ശ്രേണികൾ',
    averageTemp: 'ശരാശരി താപനില',
    moistureAverage: 'ഈർപ്പം ശരാശരി',
    precipitation: 'മഴ',
    dominantHarvestSeason: 'പ്രബലമായ വിളവെടുപ്പ് സീസൺ',
    aiPredictiveConsistency: 'AI പ്രവചന സ്ഥിരത',
    evaluatedAcross: 'ഉടനീളം വിലയിരുത്തി',
    chartProfile: 'ചാർട്ട് പ്രൊഫൈൽ',
    predictionHistoricalTimeline: 'പ്രെഡിക്ഷൻ ഹിസ്റ്റോറിക്കൽ ടൈംലൈൻ',
    realTimeChronoTimeline: 'റിയൽ-ടൈം ക്രോണോ ടൈംലൈൻ',
    nitrogenAvg: 'നൈട്രജൻ ശരാശരി',
    phosphorusAvg: 'ഫോസ്ഫറസ് ശരാശരി',
    potassiumAvg: 'പൊട്ടാസ്യം ശരാശരി',
    sensorDiagnostic: 'സെൻസർ ഡയഗ്നോസ്റ്റിക്',
    macronutrientBalance: 'മാക്രോ ന്യൂട്രിയൻ്റ് ബാലൻസ്',
    optimalSoilType: 'ഒപ്റ്റിമൽ മണ്ണ് തരം',
    diagnosticRiskProfile: 'ഡയഗ്നോസ്റ്റിക് റിസ്ക് പ്രൊഫൈൽ',
    extremePHWarning: 'മുന്നറിയിപ്പ്: എക്‌സ്ട്രീം pH പ്രൊഫൈൽ കണ്ടെത്തി',
    phAlkalinityOptimum: 'pH ആൽക്കലിനിറ്റി സൂചിക ഒപ്റ്റിമൽ',
    basedOnPHCalculations: 'ശരാശരി pH ലെവൽ കണക്കുകൂട്ടലുകൾ അടിസ്ഥാനമാക്കി.',
    npkHeatmapIndex: 'NPK ഹീറ്റ്‌മാപ്പ് സൂചിക',
    macronutrientAllocationMatrix: 'മാക്രോ ന്യൂട്രിയൻ്റ് അലോക്കേഷൻ മെട്രിക്സ്',
    allocatedIndicesNotice: '*അനുവദിച്ച സൂചികകൾ തുടർച്ചയായ പ്രവചന ചക്രങ്ങളിലുടനീളം വേർതിരിച്ചെടുത്ത ആപേക്ഷിക രാസ അനുപാതങ്ങളെ പ്രതിനിധീകരിക്കുന്നു.',
    dynamicAIInsights: 'ഡൈനാമിക് എഐ ഇൻസൈറ്റുകൾ',
    aiInsightsVerified: 'AgroXAI കോഗ്നിറ്റീവ് ഓപ്പറേഷൻസ് പരിശോധിച്ചു',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    soilHealthOverview: 'മണ്ണിൻ്റെ ആരോഗ്യ അവലോകനം',
    precisionAnalysisHistory: 'കൃത്യമായ വിശകലന ചരിത്രം',
    muskmelon: 'മസ്‌ക്‌മെലൺ',
    chickpea: 'ചെറുപയർ',
    rice: 'അരി',
    cotton: 'പരുത്തി',
    wheat: 'ഗോതമ്പ്',
    insight1Detail: 'ചരിത്രപരമായ പ്രവചനങ്ങൾ മണ്ണ് പ്രൊഫൈൽ സൂചികകളിൽ ഉയർന്ന എൻസൈമാറ്റിക് അനുയോജ്യത സ്ഥിരീകരിക്കുന്നു.',
    insight2GrowthDetail: 'ഫോളിയർ വോളിയം ബെഞ്ച്മാർക്കുകൾ മികച്ച നൈട്രജൻ ആഗിരണം ഗുണകങ്ങൾ കാണിക്കുന്നു.',
    insight2WarningDetail: 'മാക്രോ ന്യൂട്രിയൻ്റ് കുറവുകൾ കോർ ഫോട്ടോസിന്തറ്റിക് ഔട്ട്പുട്ട് വേഗതയെ പരിമിതപ്പെടുത്തുന്നു.',
    insight3Detail: 'കാലാവസ്ഥാ ടെലിമെട്രി വെക്‌ടറുകൾ സീസണൽ ഈർപ്പം പരിധിക്ക് തികച്ചും അനുയോജ്യമാണ്.',
  },
  pa: {
    selectLanguage: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    selectSubtitle: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਵਿੱਚ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਇੱਕ ਭਾਸ਼ਾ ਚੁਣো',
    continueBtn: 'ਜਾਰੀ ਰੱਖੋ',
    searchPlaceholder: 'ਭਾਸ਼ਾ ਖੋਜੋ...',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲो',
    navHome: 'ਹੋਮ',
    navRecommend: 'ਸਿਫਾਰਿਸ਼',
    navHistory: 'ਇਤਿਹਾਸ',
    welcomeBack: 'ਵਾਪਸ ਜੀ ਆਇਆਂ',
    loginTitle: 'ਲਾਗਇਨ',
    username: 'ਉਪਭੋਗਤਾ ਨਾਮ',
    password: 'ਪਾਸਵਰਡ',
    loginBtn: 'ਲਾਗਇਨ ਕਰੋ',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ?',
    signUp: 'ਸਾਈਨ ਅਪ',
    logout: 'ਲੌਗ ਆਊਟ',
    allLanguages: 'ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ',
    navMyFarm: 'ਮੇਰਾ ਫਾਰਮ',
    navIntelligence: 'ਬੁੱਧੀ',
    myFarmTitle: 'ਮੇਰਾ ਫਾਰਮ',
    myFarmSubtitle: 'ਆਪਣੇ ਖੇਤਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ, ਆਪਣੀ ਮਿੱਟੀ ਨੂੰ ਟਰੈਕ ਕਰੋ, ਅਤੇ ਹਰ ਮੌਸਮ ਵਿੱਚ ਚੁਸਤ ਯੋਜਨਾ ਬਣਾਓ।',
    claySoil: 'ਮਿੱਟੀ ਦੀ ਮਿੱਟੀ',
    sandySoil: 'ਰੇਤਲੀ ਮਿੱਟੀ',
    loamySoil: 'ਲੋਮੀ ਮਿੱਟੀ',
    blackSoil: 'ਕਾਲੀ ਮਿੱਟੀ',
    redSoil: 'ਲਾਲ ਮਿੱਟੀ',
    alluvialSoil: 'ਐਲੂਵੀਅਲ ਮਿੱਟੀ',
    saveFieldBtn: 'ਫੀਲਡ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    logCropBtn: 'ਲੌਗ ਕਰੋਪ',
    addNewField: '+ ਨਵਾਂ ਖੇਤਰ ਸ਼ਾਮਲ ਕਰੋ',
    logPastCrop: 'ਲੌਗ ਪਿਛਲੀ ਫਸਲ',
    myFieldsHeader: 'ਮੇਰੇ ਖੇਤਰ',
    farmOverviewHeader: 'ਫਾਰਮ ਦੀ ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    totalFieldsLabel: 'ਕੁੱਲ ਖੇਤਰ',
    totalAcresLabel: 'ਕੁੱਲ ਏਕੜ',
    soilTypesLabel: 'ਮਿੱਟੀ ਦੀਆਂ ਕਿਸਮਾਂ',
    mostUsedLabel: 'ਸਭ ਤੋਂ ਵੱਧ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ',
    cropHistoryHeader: 'ਕ੍ਰੌਪ ਇਤਿਹਾਸ',
    quickInsightsHeader: 'ਤਤਕਾਲ ਇਨਸਾਈਟਸ',
    analyzeBtn: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    kharif: 'ਸਾਉਣੀ',
    rabi: 'ਰਬੀ',
    zaid: 'ਜ਼ੈਦ',
    goodYield: 'ਚੰਗੀ ਉਪਜ',
    averageYield: 'ਔਸਤ',
    poorYield: 'ਗਰੀਬ',
    addField: 'ਖੇਤਰ ਸ਼ਾਮਲ ਕਰੋ',
    runAnalysis: 'ਵਿਸ਼ਲੇਸ਼ਣ ਚਲਾਓ',
    viewHistory: 'ਇਤਿਹਾਸ ਦੇਖੋ',
    activeCropsLabel: 'ਕਿਰਿਆਸ਼ੀਲ ਫਸਲਾਂ',
    cropRecordsLabel: 'ਫਸਲ ਰਿਕਾਰਡ',
    riskLevelLabel: 'ਜੋਖਮ ਪੱਧਰ',
    successRate: 'ਸਫਲਤਾ ਦਰ',
    farmIntelligenceSystem: 'ਫਾਰਮ ਇੰਟੈਲੀਜੈਂਸ ਸਿਸਟਮ',
    cropIntelligence: 'ਕ੍ਰੌਪ ਇੰਟੈਲੀਜੈਂਸ',
    cropIntelligenceSubtitle: 'ਤੁਹਾਡੇ ਇਤਿਹਾਸਕ ਭਵਿੱਖਬਾਣੀ ਲੌਗਾਂ ਨੂੰ ਭਵਿੱਖਬਾਣੀ ਵਿਸ਼ਲੇਸ਼ਣ ਵਿੱਚ ਬਦਲਣਾ। ਓਪਰੇਟਿੰਗ ਸਿਸਟਮ ਨੂੰ ਅਨੁਕੂਲਿਤ ਫਸਲ ਡਾਇਗਨੌਸਟਿਕਸ ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਰੂਪ ਦੇਣ ਲਈ ਹੇਠਾਂ ਦਿੱਤੀ ਕੋਈ ਵੀ ਫਸਲ ਚੁਣੋ।',
    syncAtlasData: 'ਐਟਲਸ ਡਾਟਾ ਸਿੰਕ ਕਰੋ',
    noAnalyticsFootprint: 'ਕੋਈ ਵਿਸ਼ਲੇਸ਼ਣ ਫੁਟਪ੍ਰਿੰਟ ਨਹੀਂ ਮਿਲਿਆ',
    noAnalyticsFootprintSubtitle: 'ਇਹ ਵਿਸ਼ਲੇਸ਼ਣ ਕੇਂਦਰ ਤੁਹਾਡੇ ਸਿਫ਼ਾਰਿਸ਼ ਲੌਗਾਂ ਤੋਂ ਗਤੀਸ਼ੀਲ ਤੌਰ \'ਤੇ ਫਸਲਾਂ ਦੇ ਅੰਕੜਿਆਂ ਨੂੰ ਕੰਪਾਇਲ ਕਰਦਾ ਹੈ। ਇਹਨਾਂ ਨਿਊਰਲ ਵਿਜੇਟਸ ਨੂੰ ਬੂਟ ਕਰਨ ਲਈ ਮਿੱਟੀ ਦੀ ਜਾਂਚ ਦੀ ਸਿਫ਼ਾਰਿਸ਼ ਕਰੋ!',
    generateFirstRecommendation: 'ਪਹਿਲੀ ਸਿਫ਼ਾਰਸ਼ ਤਿਆਰ ਕਰੋ',
    selectLoggedCropProfile: 'ਲੌਗਡ ਕ੍ਰੌਪ ਪ੍ਰੋਫਾਈਲ ਚੁਣੋ',
    metricMatrix: 'ਮੈਟ੍ਰਿਕ ਮੈਟ੍ਰਿਕਸ',
    climaticRanges: 'ਮੌਸਮੀ ਰੇਂਜਾਂ',
    averageTemp: 'ਔਸਤ ਤਾਪਮਾਨ',
    moistureAverage: 'ਨਮੀ ਔਸਤ',
    precipitation: 'ਵਰਖਾ',
    dominantHarvestSeason: 'ਪ੍ਰਮੁੱਖ ਵਾਢੀ ਦਾ ਸੀਜ਼ਨ',
    aiPredictiveConsistency: 'AI ਭਵਿੱਖਬਾਣੀ ਇਕਸਾਰਤਾ',
    evaluatedAcross: 'ਭਰ ਵਿੱਚ ਮੁਲਾਂਕਣ ਕੀਤਾ',
    chartProfile: 'ਚਾਰਟ ਪ੍ਰੋਫਾਈਲ',
    predictionHistoricalTimeline: 'ਭਵਿੱਖਬਾਣੀ ਇਤਿਹਾਸਕ ਸਮਾਂਰੇਖਾ',
    realTimeChronoTimeline: 'ਰੀਅਲ-ਟਾਈਮ ਕ੍ਰੋਨੋ ਟਾਈਮਲਾਈਨ',
    nitrogenAvg: 'ਨਾਈਟ੍ਰੋਜਨ ਔਸਤ',
    phosphorusAvg: 'ਫਾਸਫੋਰਸ ਔਸਤ',
    potassiumAvg: 'ਪੋਟਾਸ਼ੀਅਮ ਔਸਤ',
    sensorDiagnostic: 'ਸੈਂਸਰ ਡਾਇਗਨੌਸਟਿਕ',
    macronutrientBalance: 'ਮੈਕਰੋਨਿਊਟ੍ਰੀਐਂਟ ਬੈਲੇਂਸ',
    optimalSoilType: 'ਅਨੁਕੂਲ ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    diagnosticRiskProfile: 'ਡਾਇਗਨੌਸਟਿਕ ਜੋਖਮ ਪ੍ਰੋਫਾਈਲ',
    extremePHWarning: 'ਚੇਤਾਵਨੀ: ਬਹੁਤ ਜ਼ਿਆਦਾ pH ਪ੍ਰੋਫਾਈਲ ਖੋਜਿਆ ਗਿਆ',
    phAlkalinityOptimum: 'pH ਖਾਰੀਤਾ ਸੂਚਕਾਂਕ ਸਰਵੋਤਮ',
    basedOnPHCalculations: 'ਔਸਤ pH ਪੱਧਰ ਦੀ ਗਣਨਾ ਦੇ ਆਧਾਰ \'ਤੇ।',
    npkHeatmapIndex: 'NPK ਹੀਟਮੈਪ ਸੂਚਕਾਂਕ',
    macronutrientAllocationMatrix: 'ਮੈਕਰੋਨਿਊਟ੍ਰੀਐਂਟ ਅਲੋਕੇਸ਼ਨ ਮੈਟਰਿਕਸ',
    allocatedIndicesNotice: '*ਅਲਾਟ ਕੀਤੇ ਸੂਚਕਾਂਕ ਕ੍ਰਮਵਾਰ ਪੂਰਵ-ਅਨੁਮਾਨ ਚੱਕਰਾਂ ਵਿੱਚ ਕੱਢੇ ਗਏ ਸਾਪੇਖਿਕ ਰਸਾਇਣਕ ਅਨੁਪਾਤ ਨੂੰ ਦਰਸਾਉਂਦੇ ਹਨ।',
    dynamicAIInsights: 'ਡਾਇਨਾਮਿਕ ਏਆਈ ਇਨਸਾਈਟਸ',
    aiInsightsVerified: 'AgroXAI ਬੋਧਾਤਮਕ ਸੰਚਾਲਨ ਪ੍ਰਮਾਣਿਤ',
    recentActivity: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    soilHealthOverview: 'ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਬਾਰੇ ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    precisionAnalysisHistory: 'ਸ਼ੁੱਧਤਾ ਵਿਸ਼ਲੇਸ਼ਣ ਇਤਿਹਾਸ',
    muskmelon: 'ਕਸਤੂਰੀ',
    chickpea: 'ਛੋਲੇ',
    rice: 'ਚਾਵਲ',
    cotton: 'ਕਪਾਹ',
    wheat: 'ਕਣਕ',
    insight1Detail: 'ਇਤਿਹਾਸਕ ਭਵਿੱਖਬਾਣੀਆਂ ਮਿੱਟੀ ਪ੍ਰੋਫਾਈਲ ਸੂਚਕਾਂਕ ਵਿੱਚ ਉੱਚ ਐਨਜ਼ਾਈਮੈਟਿਕ ਅਨੁਕੂਲਤਾ ਦੀ ਪੁਸ਼ਟੀ ਕਰਦੀਆਂ ਹਨ।',
    insight2GrowthDetail: 'ਫੋਲੀਅਰ ਵਾਲੀਅਮ ਬੈਂਚਮਾਰਕ ਸ਼ਾਨਦਾਰ ਨਾਈਟ੍ਰੋਜਨ ਸਮਾਈ ਗੁਣਾਂਕ ਦਿਖਾਉਂਦੇ ਹਨ।',
    insight2WarningDetail: 'ਮੈਕਰੋਨਿਊਟ੍ਰੀਐਂਟ ਦੀ ਕਮੀ ਕੋਰ ਫੋਟੋਸਿੰਥੈਟਿਕ ਆਉਟਪੁੱਟ ਵੇਗ ਨੂੰ ਸੀਮਿਤ ਕਰਦੀ ਹੈ।',
    insight3Detail: 'ਮੌਸਮੀ ਟੈਲੀਮੈਟਰੀ ਵੈਕਟਰ ਮੌਸਮੀ ਨਮੀ ਦੀ ਸੀਮਾ ਨੂੰ ਪੂਰੀ ਤਰ੍ਹਾਂ ਫਿੱਟ ਕਰਦੇ ਹਨ।',
  },
};

// Get translation for a key, fallback to English
export const getTranslation = (lang, key) => {
  return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['en'][key] ?? key;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('cv_language') || 'en';
  });
  const [languageSelected, setLanguageSelected] = useState(() => {
    return localStorage.getItem('cv_language_selected') === 'true';
  });

  const selectLanguage = (code) => {
    setLanguage(code);
    setLanguageSelected(true);
    localStorage.setItem('cv_language', code);
    localStorage.setItem('cv_language_selected', 'true');
  };

  const resetLanguageSelection = () => {
    setLanguageSelected(false);
    localStorage.removeItem('cv_language_selected');
  };

  const t = (key) => getTranslation(language, key);

  const currentLanguage = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{
      language,
      languageSelected,
      currentLanguage,
      selectLanguage,
      resetLanguageSelection,
      t,
      LANGUAGES,
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
